#!/usr/bin/env python3
"""Regenerate lebedev_data.inc from scipy.integrate.lebedev_rule (BSD-3,
itself derived from the Lebedev-Laikov tables).  Weights are normalised to
sum to 1.  Usage: gen_lebedev.py > lebedev_data.inc"""
import numpy as np
from scipy.integrate import lebedev_rule
want = {6, 14, 26, 38, 50, 74, 86, 110, 146, 170, 194, 230, 266, 302, 350, 434, 590, 770, 974}
seen = {}
for n in range(1, 132):
    try:
        x, w = lebedev_rule(n)
    except Exception:
        continue
    if x.shape[1] in want and x.shape[1] not in seen:
        seen[x.shape[1]] = (n, x, w)
print("// Generated by tools/gen_lebedev.py from scipy.integrate.lebedev_rule; do not edit.")
print("// Lebedev-Laikov angular quadrature: rows {x, y, z, weight}; weights sum to 1.")
for npts in sorted(seen):
    n, x, w = seen[npts]
    w = w / w.sum()
    print(f"static const double leb_{npts}[][4] = {{")
    for k in range(npts):
        print("{%.17g,%.17g,%.17g,%.17g}," % (x[0, k], x[1, k], x[2, k], w[k]))
    print("};")
print("struct LebEntry { int npts; int degree; const double (*data)[4]; };")
print("static const LebEntry leb_registry[] = {")
for npts in sorted(seen):
    print(f"  {{{npts}, {seen[npts][0]}, leb_{npts}}},")
print("};")
