"""End-to-end cases: run a real code, assert what reaches the far end.

A case here stores an INPUT DECK, not captured output -- the opposite of
tests/parsers, and the whole point.  The output is regenerated by the
code on every run, so a code upgrade that changes its wording fails an
assertion here instead of silently producing a missing property months
later.  That is the shape of #80 (Gaussian 16 dropped "atomic" from
"Mulliken atomic charges" and the property was never extracted again,
with no error anywhere).

Assertions are deliberately loose about exact numbers and strict about
structure.  Pinning an energy to ten digits would make this suite fail
on a code upgrade for a reason nobody needs to care about; pinning that
ORBENG has the same length as ORBOCC catches the bug class that actually
bites (see MoPanel::fillTable(), which reverses those vectors
independently and indexes both by the same row).
"""

import os

from pipeline import sect

HERE = os.path.dirname(os.path.abspath(__file__))


def expect_mopac_ch4(props, report):
    """CH4, PM7, VECTORS ALLVEC -- the whole MO chain in one job."""
    orbeng = props.get('ORBENG', [])
    orbocc = props.get('ORBOCC', [])
    orbsym = props.get('ORBSYM', [])
    mo = props.get('MO', [])

    report.check(bool(orbeng), 'ORBENG extracted')
    report.check(bool(orbocc), 'ORBOCC extracted')
    report.check(bool(orbsym), 'ORBSYM extracted')
    report.check(bool(mo), 'MO coefficients extracted')
    if not (orbeng and orbocc and mo):
        return

    n_eng = len(sect(orbeng[-1], 'values').split())
    n_occ = len(sect(orbocc[-1], 'values').split())
    n_sym = len(sect(orbsym[-1], 'values').split()) if orbsym else 0

    #  CH4 in MOPAC's minimal valence basis: C contributes s,px,py,pz and
    #  each H one s, so eight orbitals.  Hard-coded because it is a
    #  property of the molecule and the Hamiltonian, not of a captured
    #  file -- if this changes, something real changed.
    report.check(n_eng == 8, 'ORBENG has 8 orbitals (got %d)' % n_eng)

    #  THE INVARIANT THAT MATTERS.  MoPanel::fillTable() reverses the
    #  energy, occupancy and symmetry vectors independently and then
    #  indexes all three by the same row, so unequal lengths do not run
    #  out at the end -- a short occupancy vector reads past its end and
    #  a short symmetry vector mislabels every row.
    report.check(n_occ == n_eng,
                 'ORBOCC length matches ORBENG (%d vs %d)' % (n_occ, n_eng))
    report.check(n_sym == n_eng,
                 'ORBSYM length matches ORBENG (%d vs %d)' % (n_sym, n_eng))

    #  Eight valence electrons -> four doubly occupied orbitals.
    occ = [float(x) for x in sect(orbocc[-1], 'values').split()]
    report.check(abs(sum(occ) - 8.0) < 1e-6,
                 'occupancies sum to 8 electrons (got %g)' % sum(occ))
    report.check(occ[:4] == [2.0] * 4 and occ[4:] == [0.0] * 4,
                 'four filled levels then virtuals')

    #  THE GRAPHF FILE MUST BE THE SOURCE, not the printed eigenvector
    #  block.  Both parse types emit these keys and the File= one is
    #  delivered last, so it wins -- but only if MOPAC actually wrote it
    #  and mopac.desc's File= name matched, neither of which is visible
    #  from the values alone.
    #
    #  The tell is precision: mopac.mo prints six decimals because that
    #  is all the printed block has, mopac.mgf prints eight because the
    #  GRAPHF file carries Fortran doubles.  A value that stops at six
    #  means the fallback ran and the better source was missed.
    decimals = max(len(t.split('.')[1]) for t in
                   sect(orbeng[-1], 'values').split() if '.' in t)
    report.check(decimals >= 8,
                 'ORBENG came from the GRAPHF file, not the printed block '
                 '(%d decimals; 6 means the fallback ran)' % decimals)

    #  Energies must be in Hartree, not the eV MOPAC prints.  MoPanel
    #  hard-codes its column label to "Energy Hartree", so a missing
    #  conversion shows numbers 27x too large with no error at all.
    eng = [float(x) for x in sect(orbeng[-1], 'values').split()]
    report.check(sect(orbeng[-1], 'units') == 'Hartree',
                 'ORBENG units are Hartree (got %r)'
                 % sect(orbeng[-1], 'units'))
    report.check(-5.0 < eng[0] < 0.0,
                 'lowest orbital energy is a plausible Hartree value '
                 '(got %g; ~-0.92 expected, ~-25 would mean eV)' % eng[0])

    #  The MO table must be square in this basis and complete.  A short
    #  table is rejected by PropTable on load with "input vector length
    #  does not match rows*columns", which presents as the Orbitals panel
    #  simply refusing to compute (#108).
    size = (sect(mo[-1], 'size') or '')
    report.check(size.split() == ['8', '8'],
                 'MO table is 8x8 (got %r)' % size)
    n_vals = len(sect(mo[-1], 'values').split())
    report.check(n_vals == 64,
                 'MO table has rows*columns values (got %d, want 64)' % n_vals)


def expect_mopac_ch4_thermo(props, report):
    """CH4, PM7 FORCE THERMO -- thermochemistry into the Energies panel."""
    for key in ('ENTHALPY', 'ETHERM', 'ENTROPY', 'HEATCAP', 'THERMOTEMP',
                'EZEROPT'):
        report.check(bool(props.get(key)), '%s extracted' % key)
    if not all(props.get(k) for k in ('ENTHALPY', 'ETHERM', 'THERMOTEMP')):
        return

    temp = float(sect(props['THERMOTEMP'][-1], 'values'))
    #  MOPAC prints 298 K FIRST and then scans upward from 200 K, so any
    #  "take the last stanza" reading reports the top of the scan as room
    #  temperature -- plausible numbers, wrong temperature, no error.
    report.check(abs(temp - 298.0) < 1.0,
                 'thermochemistry is at 298 K (got %g)' % temp)

    h = float(sect(props['ENTHALPY'][-1], 'values'))
    u = float(sect(props['ETHERM'][-1], 'values'))
    #  H = U + RT, the relation ORCA states explicitly and MOPAC's own
    #  E_SCF equation implies.  This is what keeps ETHERM from being
    #  "corrected" back to the table's ENTHALPY column, which is a
    #  zero-point-free correction rather than a total.
    rt = (1.987204259 * temp / 1000.0) / 627.5094740631
    report.check(abs((h - u) - rt) < 1e-9,
                 'ENTHALPY - ETHERM equals RT (got %.10f, want %.10f)'
                 % (h - u, rt))

    #  Zero-point energy must still be its own property.  It is inside
    #  ENTHALPY and ETHERM (MOPAC's heat of formation contains it), and
    #  also reported separately, as for every other code.
    zpe = float(sect(props['EZEROPT'][-1], 'values'))
    report.check(zpe > 0.0, 'EZEROPT is positive (got %g)' % zpe)


def expect_nwchem_h2o(props, report):
    """Water, B3LYP/6-31G* -- and the regression guard for #126.

    NWChem does NOT write its properties to stdout.  nwchem.desc matches
    a separate machine-tagged trace file that NWChem writes itself, via
    its built-in `ecce_print <file>` directive -- so the deck carries
    that line and the monitor is pointed at the trace, not the .out.
    Auditing nwchem.desc against plain NWChem stdout instead wrongly
    concludes the whole file is dead.
    """
    for key in ('TE', 'ORBENG', 'ORBOCC', 'MO', 'GEOMTRACE', 'DIPOLE'):
        report.check(bool(props.get(key)), '%s extracted' % key)

    #  THE #126 GUARD.  nwchem.symlab writes $key/parseSym and
    #  nwchem.molab reads it, exiting 0 without a word when it is
    #  missing.  The monitor used to flush buffered blocks in Perl hash
    #  order, randomized per process, so which ran first was a coin flip
    #  -- roughly three runs in eight produced no symmetries at all,
    #  from the same output file, with no error.  It now flushes in
    #  descriptor-file order and nwchem.desc puts [SYMLAB] ahead of
    #  [MOLAB1..5].
    #
    #  This assertion is why the case exists.  If it starts failing
    #  intermittently, the ordering guarantee has been lost again.
    report.check(bool(props.get('ORBSYM')),
                 'ORBSYM extracted (#126: needs SYMLAB flushed before '
                 'MOLAB, which is descriptor-file order)')
    if not (props.get('ORBENG') and props.get('ORBSYM')):
        return

    n_eng = len(sect(props['ORBENG'][-1], 'values').split())
    n_sym = len(sect(props['ORBSYM'][-1], 'values').split())
    report.check(n_sym == n_eng,
                 'ORBSYM length matches ORBENG (%d vs %d)' % (n_sym, n_eng))

    #  The deck says noautosym, so every orbital is in the trivial
    #  irrep.  A run that produced anything else would mean the label
    #  table and the integer indices had come apart.
    syms = set(sect(props['ORBSYM'][-1], 'values').split())
    report.check(syms == {'a'},
                 'C1 geometry gives all-"a" symmetries (got %s)'
                 % sorted(syms))

    #  Water/6-31G* is 19 basis functions; B3LYP total energy is around
    #  -76.4 Hartree.  Loose on purpose -- the point is that a real
    #  number in the right region arrived, not that it matches to ten
    #  digits across NWChem releases.
    te = float(sect(props['TE'][-1], 'values'))
    report.check(-77.0 < te < -76.0,
                 'total energy is a plausible B3LYP/6-31G* value for water '
                 '(got %g)' % te)


CASES = [
    dict(
        name='mopac-ch4-mos',
        code='mopac',
        desc='mopac.desc',
        deck='mopac/mos/mopac.mop',
        #  ". <runtype> <theory category> <theory name> <open shells>",
        #  as DavCalculation::getParseScriptArgs builds it.
        parse_args=('.', 'Energy', 'SE', 'PM7', '0'),
        output='mopac.out',
        expect=expect_mopac_ch4,
    ),
    dict(
        name='mopac-ch4-thermo',
        code='mopac',
        desc='mopac.desc',
        deck='mopac/thermo/mopac.mop',
        parse_args=('.', 'Vibration', 'SE', 'PM7', '0'),
        output='mopac.out',
        expect=expect_mopac_ch4_thermo,
    ),
    dict(
        #  NWChem reads its properties from a SEPARATE trace file, not
        #  stdout -- see expect_nwchem_h2o.  `output` is therefore the
        #  ecce_print target named in the deck.
        name='nwchem-h2o-dft',
        code='nwchem',
        desc='nwchem.desc',
        deck='nwchem/h2o_dft.nw',
        parse_args=('.', 'Energy', 'DFT', 'B3LYP', '0'),
        output='ecce.out',
        expect=expect_nwchem_h2o,
    ),
]


#  How to find and invoke each code.  A code that is absent is SKIPPED
#  with its name reported, never silently passed -- an e2e suite that
#  quietly tests nothing is worse than no e2e suite.
CODES = {
    'nwchem': dict(
        binary='nwchem',
        #  Debian's nwchem-openmpi ships /usr/bin/nwchem AND
        #  /usr/bin/nwchem.openmpi; other images ship only the
        #  variant-suffixed name, which is how this silently skipped in
        #  CI while the apt step reported success.
        search=('/usr/bin/nwchem', '/usr/bin/nwchem.openmpi',
                '/usr/bin/nwchem.mpich'),
        argv=lambda exe, deck: [exe, deck],
        packaged='nwchem-openmpi (or nwchem)',
    ),
    'mopac': dict(
        binary='mopac',
        search=(),
        argv=lambda exe, deck: [exe, deck],
        #  MOPAC derives its output name by stripping the input's
        #  extension, so the deck name determines the output name.
        packaged='mopac',
    ),
}
