//////////////////////////////////////////////////////////////////////////////
// SOURCE FILENAME: MessageHelper
//
// DESIGN: Helps keep track of whether messages are suspended for a given
//         subscriber.
//
//////////////////////////////////////////////////////////////////////////////
package gov.pnnl.emsl.ecce.jms;


// Includes:
import java.util.HashMap;


public class MessageHelper {

  // DATA MEMBERS:
     public static final int MAX_PACKET_LENGTH = 4096;

     private static HashMap<String,String> suspendedSubscribers;

     // Shared secret of this session; every datagram in either direction
     // starts with it. Generated by the relay, handed to apps in the port file.
     private static final String token = newToken();
     private static boolean reportedBadPacket = false;


 // STATIC INITIALIZATION:
    static {
         suspendedSubscribers = new HashMap<String,String>();
    }

  // MEMBER FUNCTIONS:

   private static String newToken() {
       byte[] b = new byte[16];
       new java.security.SecureRandom().nextBytes(b);
       StringBuilder sb = new StringBuilder();
       for (byte x : b) sb.append(String.format("%02x", x));
       return sb.toString();
   }

   public static String getToken() {
       return token;
   }

   /** The wire form of the token, prepended to every outgoing datagram. */
   public static String tokenPrefix() {
       return "TOKENSTART" + token + "TOKENEND";
   }

   /** True if the datagram starts with this session's token. */
   public static boolean acceptPacket(String data) {
       byte[] want = tokenPrefix().getBytes(java.nio.charset.StandardCharsets.UTF_8);
       byte[] got = data.getBytes(java.nio.charset.StandardCharsets.UTF_8);
       boolean ok = got.length >= want.length;
       int diff = 0;
       for (int i = 0; ok && i < want.length; i++) diff |= want[i] ^ got[i];
       ok = ok && diff == 0;
       if (!ok) {
           synchronized (MessageHelper.class) {
               if (!reportedBadPacket) {
                   reportedBadPacket = true;
                   System.out.println("Dropped a packet without this session's "
                                      + "token (further ones are dropped silently)");
               }
           }
       }
       return ok;
   }

   /**********************************************************************
     Method:  holdMessages
     Summary: Discards all incoming messages for the given subscriber
              until resumeMessaging is called.
    **********************************************************************/
    public static synchronized void holdMessages(String data) {

        try {
          
            String subscriberID = getItem(data, "ID");
            String subscriberName = getItem(data, "NAME");
            String key = subscriberID+subscriberName;
          
            //System.out.println("Temporarily stopping messages for " + key);
  	    suspendedSubscribers.put(key, "stopped");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


   /**********************************************************************
     Method:  resumeMessaging
     Summary: Resumes incoming messages for the given subscriber.
    **********************************************************************/
    public static synchronized void resumeMessaging(String data) {

        try {
          
            String subscriberID = getItem(data, "ID");
            String subscriberName = getItem(data, "NAME");
            String key = subscriberID+subscriberName;
            
            //System.out.println("Resuming messages for " + key);
           
            if (suspendedSubscribers.containsKey(key)) {
                suspendedSubscribers.remove(key);
            } else {
                //System.out.println(
                //           "Messaging not suspended - nothing to resume!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public static boolean messagingSuspended(String subscriberID) {
        boolean ret = false;
        
        if (suspendedSubscribers.containsKey(subscriberID)) {
            ret = true;
        }
        return ret;
    }

    /*******************************************************************
      Method : getItem
      Summary: Used to retrieve a tagged item from the datagram packet.
    *******************************************************************/ 
    public static String getItem(String packetData, String itemName) {

        String starttag = itemName + "START";
        String endtag = itemName + "END";
        String ret = new String("");

        int startpos = packetData.indexOf(starttag);
        int endpos = packetData.indexOf(endtag);

        if (startpos == -1 || endpos == -1) {
            System.out.println("Invalid datagram packet format: " +
                               packetData);
        } else if (startpos + starttag.length() < endpos) {

            ret = packetData.substring(startpos + starttag.length(),
                                          endpos);
        }
        return ret;
    }
    /*******************************************************************
      Method : getIntItem
      Summary: Used to retrieve a tagged item from the datagram packet
               and convert it to an integer.
    *******************************************************************/ 
    public static int getIntItem(String packetData, String itemName) {

        String item = getItem(packetData, itemName);
        int ret = Integer.parseInt(item);
        return ret;
    }
    /*******************************************************************
      Method : getBoolItem
      Summary: Used to retrieve a tagged item from the datagram packet
               and convert it to a boolean.
    *******************************************************************/ 
    public static boolean getBoolItem(String packetData, String itemName) {

        String item = getItem(packetData, itemName);
        boolean ret = Boolean.valueOf(item).booleanValue();
        return ret;
    }

}






