"""
Seed a real calculation into the data server, so apps can be opened ON one.

Starting every app empty proves it constructs.  It cannot see the class of
bug that actually hurt most here -- #78, where `builder` segfaulted opening
any job with vibrational data, because `wxGrid::CreateGrid()` fires
`wxEVT_GRID_SELECT_CELL` synchronously during construction into a handler
whose dependencies do not exist yet.  That code path only runs when there is
`VIB` data to show.

So this installs a checked-in calculation into a throwaway data-server
account and hands back a context URL.  `fixtures/calc-water-vib/` is a real
Gaussian-16 water job (STO-3G, opt+freq) carrying VIB, VIBFREQ, VIBIR,
VIBRAM, MO, ORBENG, GEOMTRACE and the usual scalars -- enough to trigger the
vibration panel, the MO panel and the geometry-trace panel, which are three
of the four places this project has found viewer crashes.  Its `Outputs/`
directory was dropped: it is the biggest part of a calculation, nothing in
the property pipeline reads it, and it was the only part carrying absolute
paths and a real username.

Everything here is idempotent and confined to the fixture account, so a run
never touches a real user's data.

Auth: none, by design -- and that took some finding.  `httpd.conf.ecce`
grants anonymous HEAD/GET/PROPFIND at the `Ecce` level, but a PROPFIND on a
calculation collection still returns 401 for every account, because
`ecce-dataserver-adduser` writes a per-account `.htaccess` ending in
`require user <name>`, and `Ecce/users` is `AllowOverride AuthConfig Limit`
so that file wins.

Passing credentials instead turned out to be a rabbit hole: the auth-cache
key is `EcceURL::getRef() + realm`, and the realm is not the top-level
`AuthName "Ecce"` but a per-account one the adduser script synthesises from
the account's name (`AuthName Ecce-Andy.Test`).  Several plausible spellings
of that key all still 401'd.

Since the fixture owns its own account, the simpler answer is to let it
grant anonymous reads to itself: this module overwrites the generated
`.htaccess` with one that allows read methods and still denies writes.  No
credentials, no `-pipe` plumbing, no guessing at realms, and the permission
change is confined to an account that holds nothing but this fixture.

(The app does attempt a PROPPATCH on load, which is denied with 403 and is
harmless -- it is bookkeeping, not part of reading the calculation.)
"""

import os
import shutil
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")
INSTALL = "/opt/ecce"

USER = "eccetest"
PASSWORD = "eccetest"
PORT = 8096
BASE = "http://localhost:%d/Ecce/users/%s" % (PORT, USER)


def stateDir():
    home = os.environ.get("ECCE_REALUSERHOME", os.path.expanduser("~"))
    return os.path.join(home, ".ECCE", "dataserver")


def available():
    return os.path.isdir(os.path.join(FIXTURES, "calc-water-vib"))


FIRST = "Ecce"
LAST = "Test"

# Replaces the .htaccess ecce-dataserver-adduser generates. Reads are open so
# no credentials are needed; writes stay restricted so the fixture cannot be
# modified through the server.
ANONYMOUS_READ = """\
# ECCE test fixture (tests/apps) -- anonymous read-only access.
# Generated by tests/apps/fixture.py; safe to delete along with the account.
<Limit OPTIONS HEAD GET PROPFIND>
Require all granted
</Limit>
<Limit PUT DELETE PROPPATCH MKCOL COPY MOVE LOCK UNLOCK POST>
Require user eccetest
</Limit>
"""


def ensureAccount():
    """Create the fixture data-server account, idempotently.

    Uses the real ecce-dataserver-adduser rather than hand-writing the
    htpasswd entry and .htaccess, so the fixture account is indistinguishable
    from one a person would create -- including the per-account realm, which
    the auth key depends on.
    """
    adduser = os.path.join(INSTALL, "bin", "ecce-dataserver-adduser")
    if not os.access(adduser, os.X_OK):
        return "", "ecce-dataserver-adduser is not installed"
    result = subprocess.run([adduser, "-b", USER, PASSWORD, FIRST, LAST],
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            timeout=60)
    userRoot = os.path.join(stateDir(), "htdocs", "Ecce", "users", USER)
    if not os.path.isdir(userRoot):
        return "", ("%s was not created: %s"
                    % (userRoot,
                       result.stdout.decode("utf-8", "replace").strip()))
    with open(os.path.join(userRoot, ".htaccess"), "w") as handle:
        handle.write(ANONYMOUS_READ)
    return userRoot, ""


def realm(userRoot):
    """The Apache realm for this account, from its generated .htaccess."""
    path = os.path.join(userRoot, ".htaccess")
    try:
        with open(path) as handle:
            for line in handle:
                if line.startswith("AuthName"):
                    return line.split(None, 1)[1].strip().strip('"')
    except OSError:
        pass
    return ""


def install(name="calc-water-vib"):
    """Copy a fixture calculation into the fixture account's tree.

    Returns (contextUrl, error).  Replaces any previous copy so a run always
    starts from the checked-in state rather than from whatever the last run
    left behind.
    """
    source = os.path.join(FIXTURES, name)
    if not os.path.isdir(source):
        return "", "no such fixture: %s" % source
    userRoot, error = ensureAccount()
    if error:
        return "", error

    target = os.path.join(userRoot, name)
    if os.path.exists(target):
        shutil.rmtree(target)
    shutil.copytree(source, target, symlinks=True)
    return "%s/%s" % (BASE, name), ""


def authFile(path, port=PORT):
    """Write an -pipe auth file.  AuthCache unlinks it after reading."""
    userRoot = os.path.join(stateDir(), "htdocs", "Ecce", "users", USER)
    base = "http://localhost:%d/" % port
    name = realm(userRoot)
    keys = [base + name] if name else []
    # The bare server prefix as a fallback: AuthCache's BEST_URL policy
    # prefix-matches on it when the realm-qualified key misses.
    keys.append(base)
    with open(path, "w") as handle:
        handle.write("%d\n" % len(keys))
        for key in keys:
            handle.write("%s|%s|%s\n" % (key, USER, PASSWORD))
    os.chmod(path, 0o600)
    return path


def remove(name="calc-water-vib"):
    target = os.path.join(stateDir(), "htdocs", "Ecce", "users", USER, name)
    if os.path.isdir(target):
        shutil.rmtree(target)


def installedVersion():
    path = os.path.join(INSTALL, "data", "client", "config", "Version")
    try:
        with open(path) as handle:
            return handle.read().strip()
    except OSError:
        return ""


def settleUpgradeNotices():
    """Stop the one-time "layout preferences are being reset" modal.

    Builder::restoreSettings() (Builder.C:1938) shows a modal notice whenever
    the version recorded in wxbuilder.ini differs from the running one, and
    writes the new version on exit.  The suite always terminates its apps, so
    that write never happens and the modal comes back every run -- where it
    blocks the event loop BEFORE the calculation context is opened, which is
    the very thing the fixture exists to exercise.

    Recording the current version up front puts the app in the steady state a
    user is in from their second launch onward.  The one-time notice itself
    is correct behaviour and is not what these checks are about.
    """
    version = installedVersion()
    if not version:
        return
    home = os.environ.get("ECCE_REALUSERHOME", os.path.expanduser("~"))
    for name in ("wxbuilder.ini",):
        path = os.path.join(home, ".ECCE", name)
        lines = []
        if os.path.exists(path):
            with open(path) as handle:
                lines = [l for l in handle.read().splitlines()
                         if not l.startswith(("Version=", "ResetPerspective="))]
        lines = ["ResetPerspective=1", "Version=%s" % version] + lines
        with open(path, "w") as handle:
            handle.write("\n".join(lines) + "\n")
