"""
Seed a real calculation into the data server, so apps can be opened ON one.

Starting every app empty proves it constructs.  It cannot see the class of
bug that actually hurt most here -- #78, where `builder` segfaulted opening
any job with vibrational data, because `wxGrid::CreateGrid()` fires
`wxEVT_GRID_SELECT_CELL` synchronously during construction into a handler
whose dependencies do not exist yet.  That code path only runs when there is
`VIB` data to show.

So this installs a checked-in calculation into a throwaway data-server
account and hands back a context URL.  `fixtures/calc-water-vib/` is a real
Gaussian-16 water job (STO-3G, opt+freq) carrying VIB, VIBFREQ, VIBIR,
VIBRAM, MO, ORBENG, GEOMTRACE and the usual scalars -- enough to trigger the
vibration panel, the MO panel and the geometry-trace panel, which are three
of the four places this project has found viewer crashes.  Its `Outputs/`
directory was dropped: it is the biggest part of a calculation, nothing in
the property pipeline reads it, and it was the only part carrying absolute
paths and a real username.

Everything here is idempotent and confined to the fixture account, so a run
never touches a real user's data.

Auth: none, by design -- and that took some finding.  `httpd.conf.ecce`
grants anonymous HEAD/GET/PROPFIND at the `Ecce` level, but a PROPFIND on a
calculation collection still returns 401 for every account, because
`ecce-dataserver-adduser` writes a per-account `.htaccess` ending in
`require user <name>`, and `Ecce/users` is `AllowOverride AuthConfig Limit`
so that file wins.

Passing credentials instead turned out to be a rabbit hole: the auth-cache
key is `EcceURL::getRef() + realm`, and the realm is not the top-level
`AuthName "Ecce"` but a per-account one the adduser script synthesises from
the account's name (`AuthName Ecce-Andy.Test`).  Several plausible spellings
of that key all still 401'd.

Since the fixture owns its own account, the simpler answer is to let it
grant anonymous reads to itself: this module overwrites the generated
`.htaccess` with one that allows read methods and still denies writes.  No
credentials, no `-pipe` plumbing, no guessing at realms, and the permission
change is confined to an account that holds nothing but this fixture.

(The app does attempt a PROPPATCH on load, which is denied with 403 and is
harmless -- it is bookkeeping, not part of reading the calculation.)
"""

import os
import shutil
import subprocess

import apps

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")

USER = "eccetest"
PASSWORD = "eccetest"


def install_dir():
    """The installed tree under test.

    Not a hardcoded /opt/ecce: apps.INSTALL honours ECCE_TEST_HOME, which
    is how a build installed somewhere writable gets tested without root.
    This module used to disagree with the rest of the suite about that, so
    a run against a private install still created its fixture account
    with /opt/ecce's adduser -- and, with the port hardcoded below too,
    served it from the real data server.
    """
    return apps.INSTALL


def dataserverPort():
    """The data server port THIS RUN is using (see isolate.py)."""
    return int(os.environ.get("ECCE_DATASERVER_PORT", "8096"))


def base():
    return "http://localhost:%d/Ecce/users/%s" % (dataserverPort(), USER)


def stateHome():
    """The directory holding the .ECCE this run is using.

    ECCE keeps all per-user state in $ECCE_REALUSERHOME/.ECCE -- preferences,
    the JMS dispatcher's port files, and the data server's whole document
    root. Both the C++ (Ecce::realUserHome) and the shell scripts honour the
    variable, so pointing it elsewhere gives a completely independent
    instance, which isolate.py now arranges for every run by default --
    it exports both ECCE_TEST_STATE and ECCE_REALUSERHOME, along with the
    two ports and an $ECCE_HOME whose siteconfig names them.

    Reading it here rather than being told keeps this module honest about
    which instance it is seeding: when the two disagree, the fixture goes
    into one server and the apps read from another.
    """
    return os.environ.get("ECCE_REALUSERHOME",
                          os.environ.get("ECCE_TEST_STATE",
                                         os.path.expanduser("~")))


def stateDir():
    return os.path.join(stateHome(), ".ECCE", "dataserver")


def available():
    return os.path.isdir(os.path.join(FIXTURES, "calc-water-vib"))


FIRST = "Ecce"
LAST = "Test"

# Replaces the .htaccess ecce-dataserver-adduser generates. Reads are open so
# no credentials are needed; writes stay restricted so the fixture cannot be
# modified through the server.
ANONYMOUS_READ = """\
# ECCE test fixture (tests/apps) -- anonymous read-only access.
# Generated by tests/apps/fixture.py; safe to delete along with the account.
#
# Apache 2.2 syntax on purpose. The .htaccess files ecce-dataserver-adduser
# writes use Allow/Deny, which pulls in mod_access_compat, and once that is
# active a 2.4-only "Require all granted" here is overridden -- the request
# is refused with "AH01797: client denied by server configuration" even
# though the file looks correct. Match the dialect the rest of the tree
# uses rather than mixing the two.
<Limit OPTIONS HEAD GET PROPFIND>
Order allow,deny
Allow from all
# Satisfy Any: the parent <Directory ".../Ecce"> block in httpd.conf.ecce
# carries AuthType Basic and "Require valid-user", which still applies here.
# Without this, "Allow from all" satisfies only the host check and Apache
# still issues a 401 auth challenge -- a challenge, not a denial, which is
# why nothing appears in error_log and it looks like the file is ignored.
Satisfy Any
</Limit>
<Limit PUT DELETE PROPPATCH MKCOL COPY MOVE LOCK UNLOCK POST>
Order allow,deny
Allow from all
require user eccetest
</Limit>
"""


def ensureAccount():
    """Create the fixture data-server account, idempotently.

    Uses the real ecce-dataserver-adduser rather than hand-writing the
    htpasswd entry and .htaccess, so the fixture account is indistinguishable
    from one a person would create -- including the per-account realm, which
    the auth key depends on.
    """
    adduser = os.path.join(install_dir(), "bin",
                           "ecce-dataserver-adduser")
    if not os.access(adduser, os.X_OK):
        return "", "ecce-dataserver-adduser is not installed"
    result = subprocess.run([adduser, "-b", USER, PASSWORD, FIRST, LAST],
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            timeout=60)
    userRoot = os.path.join(stateDir(), "htdocs", "Ecce", "users", USER)
    if not os.path.isdir(userRoot):
        return "", ("%s was not created: %s"
                    % (userRoot,
                       result.stdout.decode("utf-8", "replace").strip()))
    with open(os.path.join(userRoot, ".htaccess"), "w") as handle:
        handle.write(ANONYMOUS_READ)
    return userRoot, ""


def ensureRealUserAccount():
    """Create the account the apps themselves will log in as.

    Every app calls EDSIServerCentral::checkServerSetup(), which reads the
    server's `users` collection and throws "A failure was detected in the
    ECCE server setup" when it cannot -- and a data server that has never
    had an account added is in exactly that state.  On a developer's box
    the account was created by hand once, years of runs ago; a run with a
    state directory of its own starts from nothing every time, so it has
    to do the same thing GETTING_STARTED tells a person to do.

    Idempotent, and confined to whatever state directory is in force.
    """
    user = os.environ.get("ECCE_REALUSER") or os.environ.get("USER") or ""
    if not user:
        return ""
    userRoot = os.path.join(stateDir(), "htdocs", "Ecce", "users", user)
    if os.path.isdir(userRoot):
        return ""
    adduser = os.path.join(install_dir(), "bin", "ecce-dataserver-adduser")
    if not os.access(adduser, os.X_OK):
        return ""
    subprocess.run([adduser, "-b", user, "ecce", "Ecce", "User"],
                   stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT,
                   timeout=60)
    return ("data server: created the %s account (a server with no account "
            "reports itself as broken to every app)" % user)


def realm(userRoot):
    """The Apache realm for this account, from its generated .htaccess."""
    path = os.path.join(userRoot, ".htaccess")
    try:
        with open(path) as handle:
            for line in handle:
                if line.startswith("AuthName"):
                    return line.split(None, 1)[1].strip().strip('"')
    except OSError:
        pass
    return ""


def install(name="calc-water-vib"):
    """Copy a fixture calculation into the fixture account's tree.

    Returns (contextUrl, error).  Replaces any previous copy so a run always
    starts from the checked-in state rather than from whatever the last run
    left behind.
    """
    source = os.path.join(FIXTURES, name)
    if not os.path.isdir(source):
        return "", "no such fixture: %s" % source
    userRoot, error = ensureAccount()
    if error:
        return "", error

    target = os.path.join(userRoot, name)
    if os.path.exists(target):
        shutil.rmtree(target)
    shutil.copytree(source, target, symlinks=True)
    return "%s/%s" % (base(), name), ""


def authFile(path, port=None):
    """Write an -pipe auth file.  AuthCache unlinks it after reading."""
    userRoot = os.path.join(stateDir(), "htdocs", "Ecce", "users", USER)
    base = "http://localhost:%d/" % (port or dataserverPort())
    name = realm(userRoot)
    keys = [base + name] if name else []
    # The bare server prefix as a fallback: AuthCache's BEST_URL policy
    # prefix-matches on it when the realm-qualified key misses.
    keys.append(base)
    with open(path, "w") as handle:
        handle.write("%d\n" % len(keys))
        for key in keys:
            handle.write("%s|%s|%s\n" % (key, USER, PASSWORD))
    os.chmod(path, 0o600)
    return path


def remove(name="calc-water-vib"):
    target = os.path.join(stateDir(), "htdocs", "Ecce", "users", USER, name)
    if os.path.isdir(target):
        shutil.rmtree(target)


def installedVersion():
    path = os.path.join(install_dir(), "data", "client", "config",
                        "Version")
    try:
        with open(path) as handle:
            return handle.read().strip()
    except OSError:
        return ""


def settleUpgradeNotices():
    """Stop the one-time "layout preferences are being reset" modal.

    Builder::restoreSettings() (Builder.C:1938) shows a modal notice whenever
    the version recorded in wxbuilder.ini differs from the running one, and
    writes the new version on exit.  The suite always terminates its apps, so
    that write never happens and the modal comes back every run -- where it
    blocks the event loop BEFORE the calculation context is opened, which is
    the very thing the fixture exists to exercise.

    Recording the current version up front puts the app in the steady state a
    user is in from their second launch onward.  The one-time notice itself
    is correct behaviour and is not what these checks are about.

    Returns a callable that puts the user's own file back: unless the run is
    isolated via ECCE_TEST_STATE, this is editing real preferences, which a
    test has no business doing permanently.
    """
    version = installedVersion()
    if not version:
        return lambda: None
    saved = []
    for name in ("wxbuilder.ini",):
        path = os.path.join(stateHome(), ".ECCE", name)
        original = None
        lines = []
        if os.path.exists(path):
            with open(path) as handle:
                original = handle.read()
            lines = [l for l in original.splitlines()
                     if not l.startswith(("Version=", "ResetPerspective="))]
        saved.append((path, original))
        lines = ["ResetPerspective=1", "Version=%s" % version] + lines
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as handle:
                handle.write("\n".join(lines) + "\n")
        except OSError:
            pass

    def restore():
        """Put the user's own preferences back.

        This file is real user state -- window layout and the recorded
        version -- and a test run has no business editing it permanently.
        """
        for path, original in saved:
            try:
                if original is None:
                    if os.path.exists(path):
                        os.remove(path)
                else:
                    with open(path, "w") as handle:
                        handle.write(original)
            except OSError:
                pass

    return restore
