atom=Na
contraction shell=D num_primitives=1 num_coefficients=1
0.175000 1.000000
atom=Mg
contraction shell=D num_primitives=1 num_coefficients=1
0.175000 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.325000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.450000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
0.550000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
0.650000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
0.750000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
0.850000 1.000000
