atom=H
contraction shell=P num_primitives=1 num_coefficients=1
1.500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.375 1.000000
atom=He
contraction shell=P num_primitives=1 num_coefficients=1
1.500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.375 1.000000
atom=Li
contraction shell=D num_primitives=1 num_coefficients=1
0.400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.100 1.000000
atom=Be
contraction shell=D num_primitives=1 num_coefficients=1
0.510 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1275 1.000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
0.802 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.2005 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
1.252 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.313 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
1.826 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.4565 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
2.584 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.646 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
2.396 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.875 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
4.608 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.152 1.000000
atom=Na
contraction shell=D num_primitives=1 num_coefficients=1
0.350000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.087500 1.000000
atom=Mg
contraction shell=D num_primitives=1 num_coefficients=1
0.350000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.087500 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.650000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.162500 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.900000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.225000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
1.100000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.275000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
1.300000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.325000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
1.500000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.375000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
1.700000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.425000 1.000000
atom=K
contraction shell=D num_primitives=1 num_coefficients=1
0.458000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.114500 1.000000
atom=Ca
contraction shell=D num_primitives=1 num_coefficients=1
0.520000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.130000 1.000000
atom=Ga
contraction shell=D num_primitives=1 num_coefficients=1
0.169000 1.000000
atom=Ge
contraction shell=D num_primitives=1 num_coefficients=1
0.228000 1.000000
atom=As
contraction shell=D num_primitives=1 num_coefficients=1
0.264000 1.000000
atom=Se
contraction shell=D num_primitives=1 num_coefficients=1
0.305000 1.000000
atom=Br
contraction shell=D num_primitives=1 num_coefficients=1
0.415000 1.000000
atom=Kr
contraction shell=D num_primitives=1 num_coefficients=1
0.395000 1.000000
