atom=H
contraction shell=P num_primitives=1 num_coefficients=1
0.750 1.000000
atom=He
contraction shell=P num_primitives=1 num_coefficients=1
0.750 1.000000
atom=Li
contraction shell=D num_primitives=1 num_coefficients=1
0.200 1.000000
atom=Be
contraction shell=D num_primitives=1 num_coefficients=1
0.255 1.000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
0.401 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
0.626 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
0.913 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
1.292 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
1.750 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
2.304 1.000000
atom=Na
contraction shell=D num_primitives=1 num_coefficients=1
0.175000 1.000000
atom=Mg
contraction shell=D num_primitives=1 num_coefficients=1
0.175000 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.325000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.450000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
0.550000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
0.650000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
0.750000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
0.850000 1.000000
atom=K
contraction shell=D num_primitives=1 num_coefficients=1
0.229000 1.000000
atom=Ca
contraction shell=D num_primitives=1 num_coefficients=1
0.260000 1.000000
atom=Ga
contraction shell=D num_primitives=1 num_coefficients=1
0.169000 1.000000
atom=Ge
contraction shell=D num_primitives=1 num_coefficients=1
0.228000 1.000000
atom=As
contraction shell=D num_primitives=1 num_coefficients=1
0.264000 1.000000
atom=Se
contraction shell=D num_primitives=1 num_coefficients=1
0.305000 1.000000
atom=Br
contraction shell=D num_primitives=1 num_coefficients=1
0.451000 1.000000
atom=Kr
contraction shell=D num_primitives=1 num_coefficients=1
0.395000 1.000000
atom=I
contraction shell=D num_primitives=1 num_coefficients=1
0.302000 1.000000
