atom=H
contraction shell=P num_primitives=1 num_coefficients=1
1.500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.375 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.0000 1.000000
atom=He
contraction shell=P num_primitives=1 num_coefficients=1
1.500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.375 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.0000 1.000000
atom=Li
contraction shell=D num_primitives=1 num_coefficients=1
0.400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.100 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.150 1.000000
atom=Be
contraction shell=D num_primitives=1 num_coefficients=1
0.510 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1275 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.260 1.000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
0.802 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.2005 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.50000 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
1.252 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.313 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.80000 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
1.826 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.4565 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.00000 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
2.584 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.646 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.40000 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
2.396 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.875 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.85000 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
4.608 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.152 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.50000 1.000000
atom=K
contraction shell=D num_primitives=1 num_coefficients=1
0.458000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.114500 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.110000 1.000000
atom=Ca
contraction shell=D num_primitives=1 num_coefficients=1
0.520000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.130000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.330000 1.000000
