atom=Li
contraction shell=D num_primitives=1 num_coefficients=1
0.200000 1.000000
atom=Be
contraction shell=D num_primitives=1 num_coefficients=1
0.400000 1.000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
0.600000 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=Na
contraction shell=D num_primitives=1 num_coefficients=1
0.175000 1.000000
atom=Mg
contraction shell=D num_primitives=1 num_coefficients=1
0.175000 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.325000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.450000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
0.550000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
0.650000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
0.750000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
0.850000 1.000000
atom=K
contraction shell=D num_primitives=1 num_coefficients=1
0.200000 1.000000E+00
atom=Ca
contraction shell=D num_primitives=1 num_coefficients=1
0.200000 1.000000E+00
atom=Sc
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Ti
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=V
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Cr
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Mn
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Fe
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Co
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Ni
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Cu
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
atom=Zn
contraction shell=F num_primitives=1 num_coefficients=1
0.800000 1.000000E+00
