atom=H
contraction shell=P num_primitives=1 num_coefficients=1
3.0000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.7500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.1875 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.0000 1.000000
atom=He
contraction shell=P num_primitives=1 num_coefficients=1
3.0000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.7500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.1875 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.0000 1.000000
atom=Li
contraction shell=D num_primitives=1 num_coefficients=1
0.800 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.050 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.150 1.000000
atom=Be
contraction shell=D num_primitives=1 num_coefficients=1
1.02000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.25500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.06375 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.260 1.000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
1.60400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.40100 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.10025 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.50000 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
2.50400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.62600 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.15650 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.80000 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
3.65200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.91300 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.22825 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.00000 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
5.16000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.29200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.32250 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.40000 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
7.0000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.7500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.43750 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.85000 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
9.2160 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.3040 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.5760 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.50000 1.000000
atom=Na
contraction shell=D num_primitives=1 num_coefficients=1
0.7000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1750 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.04375 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.15000 1.000000
atom=Mg
contraction shell=D num_primitives=1 num_coefficients=1
0.7000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1750 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.04375 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.20000 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
1.3000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.3250 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.08125 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.25000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
1.8000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.4500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1125 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.32000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
2.2000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.5500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1375 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.45000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
2.6000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.6500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1625 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.55000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
3.0000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.7500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1875 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.70000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
3.4000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.8500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.2125 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.85000 1.000000
