atom=H
contraction shell=P num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=He
contraction shell=P num_primitives=1 num_coefficients=1
1.000000 1.000000
atom=Li
contraction shell=P num_primitives=1 num_coefficients=1
0.170000 1.000000
atom=Be
contraction shell=P num_primitives=3 num_coefficients=1
3.6316917145 -.029033998305
0.71695694366 -.16877854032
0.19541932860 -.51403419628
contraction shell=P num_primitives=1 num_coefficients=1
0.06051546589 1.0000000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
0.500000 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
1.000000 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
1.200000 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
1.400000 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
1.888000 1.000000
atom=Na
contraction shell=P num_primitives=1 num_coefficients=1
0.052000 1.000000
atom=Mg
contraction shell=P num_primitives=1 num_coefficients=1
.18914796195 1.0000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.300000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.350000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
0.450000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
0.550000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
0.650000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
0.969000 1.000000
atom=K
contraction shell=P num_primitives=1 num_coefficients=1
0.041737 1.000000
atom=Ca
contraction shell=P num_primitives=1 num_coefficients=1
0.074979 1.000000
atom=Sc
contraction shell=P num_primitives=1 num_coefficients=1
0.089748 1.000000
atom=Ti
contraction shell=P num_primitives=1 num_coefficients=1
0.101561 1.000000
atom=V
contraction shell=P num_primitives=1 num_coefficients=1
0.111248 1.000000
atom=Cr
contraction shell=P num_primitives=1 num_coefficients=1
0.120675 1.000000
atom=Mn
contraction shell=P num_primitives=1 num_coefficients=1
0.127650 1.000000
atom=Fe
contraction shell=P num_primitives=1 num_coefficients=1
0.134915 1.000000
atom=Co
contraction shell=P num_primitives=1 num_coefficients=1
0.141308 1.000000
atom=Ni
contraction shell=P num_primitives=1 num_coefficients=1
0.146588 1.000000
atom=Cu
contraction shell=P num_primitives=1 num_coefficients=1
0.155065 1.000000
atom=Zn
contraction shell=P num_primitives=1 num_coefficients=1
0.162455 1.000000
atom=Ga
contraction shell=D num_primitives=1 num_coefficients=1
0.2070 1.000000
atom=Ge
contraction shell=D num_primitives=1 num_coefficients=1
0.2460 1.000000
atom=As
contraction shell=D num_primitives=1 num_coefficients=1
0.2930 1.000000
atom=Se
contraction shell=D num_primitives=1 num_coefficients=1
0.3380 1.000000
atom=Br
contraction shell=D num_primitives=1 num_coefficients=1
0.3890 1.000000
atom=Kr
contraction shell=D num_primitives=1 num_coefficients=1
0.4430 1.000000
