atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.0207 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0744 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.1560 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.2740 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.5430 1.0000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.04664 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.1400 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.2892 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.5345 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.7899 1.0000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.0261 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0157 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0431 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0843 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.2020 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.3840 1.0000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.0394 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0272 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0701 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1380 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.3190 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.5860 1.0000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.0518 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0369 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0971 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1920 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.4360 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.7880 1.0000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.0655 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0446 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.1310 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.2370 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.5170 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
1.0240 1.0000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.0806 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0550 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.1720 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.3310 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.6630 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
1.3260 1.0000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.0957 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0654 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.2130 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.4250 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.8090 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
1.6280 1.0000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.01770 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01150 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.02940 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.05090 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.10690 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.22700 1.0000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.02600 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01920 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.04680 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.07350 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.15100 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.32300 1.0000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.03350 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02530 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.06240 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.09500 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.18400 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.37200 1.0000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.04200 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02940 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.07940 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.11880 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.22000 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.47200 1.0000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.04790 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03480 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.10030 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.16400 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.27700 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.60700 1.0000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.05380 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.04020 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.12100 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.20900 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.33400 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.74200 1.0000
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.017301 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01105 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.02600 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.05110 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.11400 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.25400 1.0000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.024274 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.017593 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.03640 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.07050 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.14600 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.32000 1.0000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.029418 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.022043 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.04880 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.08990 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.16550 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.36680 1.0000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.033935 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.024975 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.05480 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.09920 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.18300 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.40200 1.0000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.039106 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.029052 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.07810 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.13880 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.21900 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.49100 1.0000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.044277 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.033129 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.10140 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.17840 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.25500 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.58000 1.0000
