atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.01770 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01150 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0254 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.05090 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.10690 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.22700 1.0000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.02600 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01920 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0390 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.07350 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.15100 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.32300 1.0000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.03350 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02530 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0537 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.09500 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.18400 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.37200 1.0000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.04200 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02940 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0664 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.11880 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.22000 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.47200 1.0000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.04790 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03480 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0836 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.16400 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.27700 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.60700 1.0000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.05380 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.04020 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0978 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.20900 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.33400 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.74200 1.0000
