atom=Sc
contraction shell=S num_primitives=1 num_coefficients=1
0.01007 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01008 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.00895 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.02482 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.04884 1.0
contraction shell=H num_primitives=1 num_coefficients=1
0.09489 1.0
contraction shell=I num_primitives=1 num_coefficients=1
0.13863 1.0
atom=Ti
contraction shell=S num_primitives=1 num_coefficients=1
0.01048 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01087 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.01127 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.04084 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.07949 1.0
contraction shell=H num_primitives=1 num_coefficients=1
0.16787 1.0
contraction shell=I num_primitives=1 num_coefficients=1
0.32089 1.0
atom=V
contraction shell=S num_primitives=1 num_coefficients=1
0.01105 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01151 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01413 1
contraction shell=F num_primitives=1 num_coefficients=1
0.05812 1
contraction shell=G num_primitives=1 num_coefficients=1
0.11893 1
contraction shell=H num_primitives=1 num_coefficients=1
0.25042 1
contraction shell=I num_primitives=1 num_coefficients=1
0.58959 1
atom=Cr
contraction shell=S num_primitives=1 num_coefficients=1
0.01151 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01212 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01669 1
contraction shell=F num_primitives=1 num_coefficients=1
0.07102 1
contraction shell=G num_primitives=1 num_coefficients=1
0.14826 1
contraction shell=H num_primitives=1 num_coefficients=1
0.32651 1
contraction shell=I num_primitives=1 num_coefficients=1
0.85889 1
atom=Mn
contraction shell=S num_primitives=1 num_coefficients=1
0.01183 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01261 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01845 1
contraction shell=F num_primitives=1 num_coefficients=1
0.08753 1
contraction shell=G num_primitives=1 num_coefficients=1
0.19253 1
contraction shell=H num_primitives=1 num_coefficients=1
0.41787 1
contraction shell=I num_primitives=1 num_coefficients=1
1.11221 1
atom=Fe
contraction shell=S num_primitives=1 num_coefficients=1
0.01229 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01279 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02044 1
contraction shell=F num_primitives=1 num_coefficients=1
0.10666 1
contraction shell=G num_primitives=1 num_coefficients=1
0.24539 1
contraction shell=H num_primitives=1 num_coefficients=1
0.52862 1
contraction shell=I num_primitives=1 num_coefficients=1
1.40499 1
atom=Co
contraction shell=S num_primitives=1 num_coefficients=1
0.01290 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01390 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02141 1
contraction shell=F num_primitives=1 num_coefficients=1
0.12655 1
contraction shell=G num_primitives=1 num_coefficients=1
0.29748 1
contraction shell=H num_primitives=1 num_coefficients=1
0.63878 1
contraction shell=I num_primitives=1 num_coefficients=1
1.70514 1
atom=Ni
contraction shell=S num_primitives=1 num_coefficients=1
0.01322 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01356 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02430 1
contraction shell=F num_primitives=1 num_coefficients=1
0.15388 1
contraction shell=G num_primitives=1 num_coefficients=1
0.36828 1
contraction shell=H num_primitives=1 num_coefficients=1
0.78798 1
contraction shell=I num_primitives=1 num_coefficients=1
2.10371 1
atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.01389 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01393 1
contraction shell=D num_primitives=1 num_coefficients=1
0.04195 1
contraction shell=F num_primitives=1 num_coefficients=1
0.17339 1
contraction shell=G num_primitives=1 num_coefficients=1
0.42637 1
contraction shell=H num_primitives=1 num_coefficients=1
0.90509 1
contraction shell=I num_primitives=1 num_coefficients=1
2.44741 1
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.01451 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01415 1
contraction shell=D num_primitives=1 num_coefficients=1
0.05661 1
contraction shell=F num_primitives=1 num_coefficients=1
0.20101 1
contraction shell=G num_primitives=1 num_coefficients=1
0.46139 1
contraction shell=H num_primitives=1 num_coefficients=1
1.06554 1
contraction shell=I num_primitives=1 num_coefficients=1
2.79414 1
