atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.0174 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.0170 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.0872 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.9066 1.0
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.0181 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.0174 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.1172 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.0870 1.0
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.0222 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0145 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0514 1.000000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.0310 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0232 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0780 1.000000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.0370 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0308 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1000 1.000000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.0433 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0345 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1260 1.000000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.0502 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0394 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1548 1.000000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.0571 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0443 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1836 1.000000
atom=Ag
contraction shell=S num_primitives=1 num_coefficients=1
0.0162 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0152 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0620 1
contraction shell=F num_primitives=1 num_coefficients=1
0.4449 1
atom=Cd
contraction shell=S num_primitives=1 num_coefficients=1
0.0167 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0153 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0782 1
contraction shell=F num_primitives=1 num_coefficients=1
0.5177 1
atom=In
contraction shell=S num_primitives=1 num_coefficients=1
0.0203 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0141 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0472 1.000000
atom=Sn
contraction shell=S num_primitives=1 num_coefficients=1
0.0275 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0209 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0649 1.000000
atom=Sb
contraction shell=S num_primitives=1 num_coefficients=1
0.0327 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0271 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0802 1.000000
atom=Te
contraction shell=S num_primitives=1 num_coefficients=1
0.0369 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0299 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0988 1.000000
atom=I
contraction shell=S num_primitives=1 num_coefficients=1
0.0421 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0339 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1196 1.000000
atom=Xe
contraction shell=S num_primitives=1 num_coefficients=1
0.0473 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0379 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1404 1.000000
atom=Au
contraction shell=S num_primitives=1 num_coefficients=1
0.0193 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0147 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0489 1
contraction shell=F num_primitives=1 num_coefficients=1
0.3789 1
atom=Hg
contraction shell=S num_primitives=1 num_coefficients=1
0.0199 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0147 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0585 1
contraction shell=F num_primitives=1 num_coefficients=1
0.4377 1
atom=Tl
contraction shell=S num_primitives=1 num_coefficients=1
0.0206 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0130 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0437 1.000000
atom=Pb
contraction shell=S num_primitives=1 num_coefficients=1
0.0278 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0197 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0609 1.000000
atom=Bi
contraction shell=S num_primitives=1 num_coefficients=1
0.0317 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0254 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0745 1.000000
atom=Po
contraction shell=S num_primitives=1 num_coefficients=1
0.0359 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0278 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0895 1.000000
atom=At
contraction shell=S num_primitives=1 num_coefficients=1
0.0404 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0313 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1073 1.000000
atom=Rn
contraction shell=S num_primitives=1 num_coefficients=1
0.0449 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0348 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1251 1.000000
