atom=Sc
contraction shell=S num_primitives=1 num_coefficients=1
0.01007 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01004 1
contraction shell=D num_primitives=1 num_coefficients=1
0.00876 1
contraction shell=F num_primitives=1 num_coefficients=1
0.02440 1
contraction shell=G num_primitives=1 num_coefficients=1
0.04905 1
contraction shell=H num_primitives=1 num_coefficients=1
0.09303 1
contraction shell=I num_primitives=1 num_coefficients=1
0.43810 1
atom=Ti
contraction shell=S num_primitives=1 num_coefficients=1
0.01048 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01084 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01157 1
contraction shell=F num_primitives=1 num_coefficients=1
0.04027 1
contraction shell=G num_primitives=1 num_coefficients=1
0.07841 1
contraction shell=H num_primitives=1 num_coefficients=1
0.16486 1
contraction shell=I num_primitives=1 num_coefficients=1
0.30842 1
atom=V
contraction shell=S num_primitives=1 num_coefficients=1
0.01105 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01149 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01445 1
contraction shell=F num_primitives=1 num_coefficients=1
0.05745 1
contraction shell=G num_primitives=1 num_coefficients=1
0.11705 1
contraction shell=H num_primitives=1 num_coefficients=1
0.24536 1
contraction shell=I num_primitives=1 num_coefficients=1
0.56650 1
atom=Cr
contraction shell=S num_primitives=1 num_coefficients=1
0.01151 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01208 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01663 1
contraction shell=F num_primitives=1 num_coefficients=1
0.07018 1
contraction shell=G num_primitives=1 num_coefficients=1
0.14563 1
contraction shell=H num_primitives=1 num_coefficients=1
0.32031 1
contraction shell=I num_primitives=1 num_coefficients=1
0.83692 1
atom=Mn
contraction shell=S num_primitives=1 num_coefficients=1
0.01183 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01257 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01825 1
contraction shell=F num_primitives=1 num_coefficients=1
0.08643 1
contraction shell=G num_primitives=1 num_coefficients=1
0.18890 1
contraction shell=H num_primitives=1 num_coefficients=1
0.40851 1
contraction shell=I num_primitives=1 num_coefficients=1
1.08855 1
atom=Fe
contraction shell=S num_primitives=1 num_coefficients=1
0.01229 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01275 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02023 1
contraction shell=F num_primitives=1 num_coefficients=1
0.10527 1
contraction shell=G num_primitives=1 num_coefficients=1
0.24096 1
contraction shell=H num_primitives=1 num_coefficients=1
0.51669 1
contraction shell=I num_primitives=1 num_coefficients=1
1.37765 1
atom=Co
contraction shell=S num_primitives=1 num_coefficients=1
0.01290 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01387 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02181 1
contraction shell=F num_primitives=1 num_coefficients=1
0.12491 1
contraction shell=G num_primitives=1 num_coefficients=1
0.29206 1
contraction shell=H num_primitives=1 num_coefficients=1
0.62431 1
contraction shell=I num_primitives=1 num_coefficients=1
1.67271 1
atom=Ni
contraction shell=S num_primitives=1 num_coefficients=1
0.01322 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01351 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02409 1
contraction shell=F num_primitives=1 num_coefficients=1
0.14611 1
contraction shell=G num_primitives=1 num_coefficients=1
0.34912 1
contraction shell=H num_primitives=1 num_coefficients=1
0.73290 1
contraction shell=I num_primitives=1 num_coefficients=1
1.99033 1
atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.01389 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01388 1
contraction shell=D num_primitives=1 num_coefficients=1
0.04128 1
contraction shell=F num_primitives=1 num_coefficients=1
0.17102 1
contraction shell=G num_primitives=1 num_coefficients=1
0.41860 1
contraction shell=H num_primitives=1 num_coefficients=1
0.88150 1
contraction shell=I num_primitives=1 num_coefficients=1
2.39472 1
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.01451 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01410 1
contraction shell=D num_primitives=1 num_coefficients=1
0.05772 1
contraction shell=F num_primitives=1 num_coefficients=1
0.19925 1
contraction shell=G num_primitives=1 num_coefficients=1
0.48887 1
contraction shell=H num_primitives=1 num_coefficients=1
1.04254 1
contraction shell=I num_primitives=1 num_coefficients=1
2.87069 1
