atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.0321008 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.019407 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.06210 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.09762 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.22020 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.22160 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.3389 1.0000
contraction shell=K num_primitives=1 num_coefficients=1
0.9780 1.0000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.0190122 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0269704 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0753692 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1202192 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.2456348 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.516365 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.790000 1.0000
contraction shell=K num_primitives=1 num_coefficients=1
0.977000 1.0000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.0554700 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0286137 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.103900 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.172627 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.345782 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.581640 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
1.039000 1.0000
contraction shell=K num_primitives=1 num_coefficients=1
1.232000 1.0000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.070009 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.034589 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.133942 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.254283 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.3958677 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.780500 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
1.080000 1.0000
contraction shell=K num_primitives=1 num_coefficients=1
1.597000 1.0000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.037179 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.021812 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.034380 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.021930 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.184380 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.303540 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.445000 1.0000
contraction shell=K num_primitives=1 num_coefficients=1
0.711000 1.0000
