atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.0189 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0670 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.1260 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.2450 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.4070 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.6820 1.0000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.04473 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.1280 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.2410 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.4070 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.6860 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
1.0160 1.0000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.02300 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01365 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.03920 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0733 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1620 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.2880 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.5000 1.0000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.03540 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02376 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.06360 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1180 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.2540 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.4510 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.7760 1.0000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.04714 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03150 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0874 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1510 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.3260 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.5870 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
1.0410 1.0000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.05935 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03380 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.1150 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1950 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.4060 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.7480 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
1.3450 1.0000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.07315 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.04760 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.1510 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.2720 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.5200 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.9850 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
1.7390 1.0000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.0869 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0566 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.1870 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.3492 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.6345 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
1.2093 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
2.1215 1.0000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.01737 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01021 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.02666 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.04625 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.08545 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.16550 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.29900 1.0000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.02539 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01694 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.04139 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.06884 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.11640 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.23510 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.42710 1.0000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.03228 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02197 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.05492 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.08710 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.14700 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.28740 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.51510 1.0000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.03893 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02648 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.06986 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1100 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1799 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.3465 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.6222 1.0000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.04625 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03163 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.08885 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.14650 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.21770 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.43650 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.8074 1.0000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.05357 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03678 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.10780 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.18300 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.25550 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.52650 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.99260 1.0000
