atom=H
contraction shell=S num_primitives=6 num_coefficients=1
82.64 0.002006
12.41 0.015343
2.824 0.075579
0.7977 0.256875
0.2581 0.497368
0.08989 0.296133
contraction shell=S num_primitives=1 num_coefficients=1
0.7382 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.2541 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.0875 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.0197 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.6514 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.8776 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.2905 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0828 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.0210 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.6644 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1875 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.4874 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.3681 1.000000
