atom=H
contraction shell=S num_primitives=7 num_coefficients=1
188.614442 0.000718
28.276596 0.005554
6.424830 0.028426
1.815041 0.109523
0.591063 0.300447
0.212149 0.474668
0.079291 0.225027
contraction shell=S num_primitives=1 num_coefficients=1
1.4853 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.5519 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.2051 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.0762 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.0179 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.9147 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.8108 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.6671 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.2458 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0740 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.9714 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.1867 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.4739 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1493 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.4915 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.8971 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.2742 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.2693 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.5373 1.000000
