atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.01737 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01021 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0237 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.04625 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.08545 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.16550 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.29900 1.0000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.02539 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01694 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0370 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.06884 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.11640 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.23510 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.42710 1.0000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.03228 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02197 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0507 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.08710 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.14700 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.28740 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.51510 1.0000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.03893 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02648 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0609 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1100 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1799 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.3465 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.6222 1.0000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.04625 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03163 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.07750 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.14650 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.21770 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.43650 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.8074 1.0000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.05357 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.03678 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0898 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.18300 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.25550 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.52650 1.0000
contraction shell=I num_primitives=1 num_coefficients=1
0.99260 1.0000
