atom=Sc
contraction shell=S num_primitives=1 num_coefficients=1
0.01047 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01008 1
contraction shell=D num_primitives=1 num_coefficients=1
0.00947 1
contraction shell=F num_primitives=1 num_coefficients=1
0.03067 1
contraction shell=G num_primitives=1 num_coefficients=1
0.07060 1
contraction shell=H num_primitives=1 num_coefficients=1
0.11931 1
atom=Ti
contraction shell=S num_primitives=1 num_coefficients=1
0.01110 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01098 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01276 1
contraction shell=F num_primitives=1 num_coefficients=1
0.05449 1
contraction shell=G num_primitives=1 num_coefficients=1
0.12313 1
contraction shell=H num_primitives=1 num_coefficients=1
0.26253 1
atom=V
contraction shell=S num_primitives=1 num_coefficients=1
0.01172 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01172 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01620 1
contraction shell=F num_primitives=1 num_coefficients=1
0.08053 1
contraction shell=G num_primitives=1 num_coefficients=1
0.18929 1
contraction shell=H num_primitives=1 num_coefficients=1
0.45499 1
atom=Cr
contraction shell=S num_primitives=1 num_coefficients=1
0.01157 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01232 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01780 1
contraction shell=F num_primitives=1 num_coefficients=1
0.10242 1
contraction shell=G num_primitives=1 num_coefficients=1
0.24002 1
contraction shell=H num_primitives=1 num_coefficients=1
0.61479 1
atom=Mn
contraction shell=S num_primitives=1 num_coefficients=1
0.01280 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01284 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01969 1
contraction shell=F num_primitives=1 num_coefficients=1
0.12624 1
contraction shell=G num_primitives=1 num_coefficients=1
0.31119 1
contraction shell=H num_primitives=1 num_coefficients=1
0.75513 1
atom=Fe
contraction shell=S num_primitives=1 num_coefficients=1
0.01348 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01302 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02186 1
contraction shell=F num_primitives=1 num_coefficients=1
0.15270 1
contraction shell=G num_primitives=1 num_coefficients=1
0.39815 1
contraction shell=H num_primitives=1 num_coefficients=1
0.93245 1
atom=Co
contraction shell=S num_primitives=1 num_coefficients=1
0.01409 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01419 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02386 1
contraction shell=F num_primitives=1 num_coefficients=1
0.18087 1
contraction shell=G num_primitives=1 num_coefficients=1
0.48521 1
contraction shell=H num_primitives=1 num_coefficients=1
1.12461 1
atom=Ni
contraction shell=S num_primitives=1 num_coefficients=1
0.01467 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01383 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02647 1
contraction shell=F num_primitives=1 num_coefficients=1
0.21526 1
contraction shell=G num_primitives=1 num_coefficients=1
0.61121 1
contraction shell=H num_primitives=1 num_coefficients=1
1.34382 1
atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.01524 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01419 1
contraction shell=D num_primitives=1 num_coefficients=1
0.04527 1
contraction shell=F num_primitives=1 num_coefficients=1
0.25007 1
contraction shell=G num_primitives=1 num_coefficients=1
0.71035 1
contraction shell=H num_primitives=1 num_coefficients=1
1.62276 1
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.01576 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01464 1
contraction shell=D num_primitives=1 num_coefficients=1
0.06500 1
contraction shell=F num_primitives=1 num_coefficients=1
0.29390 1
contraction shell=G num_primitives=1 num_coefficients=1
0.84730 1
contraction shell=H num_primitives=1 num_coefficients=1
1.96054 1
