atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.0172 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.0151 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.0604 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.4587 1.0
contraction shell=G num_primitives=1 num_coefficients=1
1.3831 1.0
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.0178 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.0154 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.0858 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.5450 1.0
contraction shell=G num_primitives=1 num_coefficients=1
1.7130 1.0
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.0187 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0126 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0351 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1019 1.00000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.0266 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0213 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0512 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1321 1.00000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.0330 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0282 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0649 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1542 1.00000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.0384 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0327 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0819 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1842 1.00000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.0445 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0396 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.1009 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.2454 1.00000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.0506 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0465 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.1199 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.3066 1.00000
atom=Ag
contraction shell=S num_primitives=1 num_coefficients=1
0.0151 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0132 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0481 1
contraction shell=F num_primitives=1 num_coefficients=1
0.2889 1
contraction shell=G num_primitives=1 num_coefficients=1
0.7090 1
atom=Cd
contraction shell=S num_primitives=1 num_coefficients=1
0.0156 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0134 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0617 1
contraction shell=F num_primitives=1 num_coefficients=1
0.3389 1
contraction shell=G num_primitives=1 num_coefficients=1
0.8344 1
atom=In
contraction shell=S num_primitives=1 num_coefficients=1
0.0180 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0124 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0302 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0895 1.00000
atom=Sn
contraction shell=S num_primitives=1 num_coefficients=1
0.0251 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0202 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0425 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1093 1.00000
atom=Sb
contraction shell=S num_primitives=1 num_coefficients=1
0.0304 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0271 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0520 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1223 1.00000
atom=Te
contraction shell=S num_primitives=1 num_coefficients=1
0.0354 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0306 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0643 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1413 1.00000
atom=I
contraction shell=S num_primitives=1 num_coefficients=1
0.0415 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0363 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0780 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1850 1.00000
atom=Xe
contraction shell=S num_primitives=1 num_coefficients=1
0.0476 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0420 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0917 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.2287 1.00000
atom=Au
contraction shell=S num_primitives=1 num_coefficients=1
0.0174 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0128 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0386 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1926 1
contraction shell=G num_primitives=1 num_coefficients=1
0.5507 1
atom=Hg
contraction shell=S num_primitives=1 num_coefficients=1
0.0181 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0128 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0470 1
contraction shell=F num_primitives=1 num_coefficients=1
0.2182 1
contraction shell=G num_primitives=1 num_coefficients=1
0.6361 1
atom=Tl
contraction shell=S num_primitives=1 num_coefficients=1
0.0183 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0122 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0294 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0990 1.00000
atom=Pb
contraction shell=S num_primitives=1 num_coefficients=1
0.0251 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0208 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0404 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1116 1.00000
atom=Bi
contraction shell=S num_primitives=1 num_coefficients=1
0.0297 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0276 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0488 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1188 1.00000
atom=Po
contraction shell=S num_primitives=1 num_coefficients=1
0.0339 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0310 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0578 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1322 1.00000
atom=At
contraction shell=S num_primitives=1 num_coefficients=1
0.0384 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0368 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0686 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1703 1.00000
atom=Rn
contraction shell=S num_primitives=1 num_coefficients=1
0.0429 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0426 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0794 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.2084 1.00000
