atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.0145 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0125 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0391 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1777 1
contraction shell=G num_primitives=1 num_coefficients=1
0.4190 1
contraction shell=H num_primitives=1 num_coefficients=1
0.8725 1
contraction shell=I num_primitives=1 num_coefficients=1
2.3576 1
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.0150 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0130 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0578 1
contraction shell=F num_primitives=1 num_coefficients=1
0.2073 1
contraction shell=G num_primitives=1 num_coefficients=1
0.4949 1
contraction shell=H num_primitives=1 num_coefficients=1
1.0334 1
contraction shell=I num_primitives=1 num_coefficients=1
2.8046 1
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.0158 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0093 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0254 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0535 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1158 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2425 1.00000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.0241 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0158 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0357 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0709 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1454 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.3051 1.00000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.0292 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0199 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0407 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0827 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1625 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.3304 1.00000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.0330 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0227 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0510 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0947 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1789 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.3906 1.00000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.0391 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0269 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0655 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1282 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2121 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.4718 1.00000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.0452 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0311 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0800 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1617 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2453 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.5530 1.00000
atom=Ag
contraction shell=S num_primitives=1 num_coefficients=1
0.0131 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0120 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0360 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1448 1
contraction shell=G num_primitives=1 num_coefficients=1
0.2596 1
contraction shell=H num_primitives=1 num_coefficients=1
0.4758 1
contraction shell=I num_primitives=1 num_coefficients=1
1.2082 1
atom=Cd
contraction shell=S num_primitives=1 num_coefficients=1
0.0134 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0124 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0419 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1669 1
contraction shell=G num_primitives=1 num_coefficients=1
0.2957 1
contraction shell=H num_primitives=1 num_coefficients=1
0.5447 1
contraction shell=I num_primitives=1 num_coefficients=1
1.4003 1
atom=In
contraction shell=S num_primitives=1 num_coefficients=1
0.0149 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0087 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0227 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0465 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.0969 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2057 1.00000
atom=Sn
contraction shell=S num_primitives=1 num_coefficients=1
0.0199 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0142 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0308 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0599 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1179 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2501 1.00000
atom=Sb
contraction shell=S num_primitives=1 num_coefficients=1
0.0240 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0175 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0368 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0667 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1284 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2615 1.00000
atom=Te
contraction shell=S num_primitives=1 num_coefficients=1
0.0271 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0199 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0449 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0755 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1395 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.3031 1.00000
atom=I
contraction shell=S num_primitives=1 num_coefficients=1
0.0305 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0229 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0530 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1030 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1628 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.3595 1.00000
atom=Xe
contraction shell=S num_primitives=1 num_coefficients=1
0.0339 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0259 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0611 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1305 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1861 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.4159 1.00000
atom=Au
contraction shell=S num_primitives=1 num_coefficients=1
0.0158 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0121 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0301 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1095 1
contraction shell=G num_primitives=1 num_coefficients=1
0.2065 1
contraction shell=H num_primitives=1 num_coefficients=1
0.3525 1
contraction shell=I num_primitives=1 num_coefficients=1
0.8919 1
atom=Hg
contraction shell=S num_primitives=1 num_coefficients=1
0.0162 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0118 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0395 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1258 1
contraction shell=G num_primitives=1 num_coefficients=1
0.2372 1
contraction shell=H num_primitives=1 num_coefficients=1
0.3915 1
contraction shell=I num_primitives=1 num_coefficients=1
0.9888 1
atom=Tl
contraction shell=S num_primitives=1 num_coefficients=1
0.0139 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0079 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0217 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0470 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.0990 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2315 1.00000
atom=Pb
contraction shell=S num_primitives=1 num_coefficients=1
0.0190 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0130 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0294 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0585 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1156 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2593 1.00000
atom=Bi
contraction shell=S num_primitives=1 num_coefficients=1
0.0233 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0160 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0348 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0635 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1236 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2543 1.00000
atom=Po
contraction shell=S num_primitives=1 num_coefficients=1
0.0252 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0178 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0415 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0717 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1323 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.2831 1.00000
atom=At
contraction shell=S num_primitives=1 num_coefficients=1
0.0269 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0205 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0510 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0978 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1525 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.3298 1.00000
atom=Rn
contraction shell=S num_primitives=1 num_coefficients=1
0.0286 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0232 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0605 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1239 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1727 1.00000
contraction shell=H num_primitives=1 num_coefficients=1
0.3765 1.00000
