atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.01830 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01210 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0274 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.05820 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.15300 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.02750 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0414 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.08460 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.21200 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.03540 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02720 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0570 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.10900 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.25000 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.04280 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03170 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0722 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.14000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.29700 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.05190 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03760 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0912 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.21700 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.37800 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.06100 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.04350 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.108 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.29400 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.45900 1.0000
