atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.0154 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.0140 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.0426 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.2615 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.7151 1.0
contraction shell=H num_primitives=1 num_coefficients=1
1.5889 1.0
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.0161 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.0143 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.0629 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.3068 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.8508 1.0
contraction shell=H num_primitives=1 num_coefficients=1
1.9086 1.0
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.0184 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0108 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0270 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0679 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1671 1.00000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.0261 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0176 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0385 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0883 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2105 1.00000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.0316 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0221 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0474 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1032 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2314 1.00000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.0359 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0253 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0597 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1193 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2602 1.00000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.0407 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0295 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0747 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1613 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.3067 1.00000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.0455 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0337 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0897 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.2033 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.3532 1.00000
atom=Ag
contraction shell=S num_primitives=1 num_coefficients=1
0.0142 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0119 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0361 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1792 1
contraction shell=G num_primitives=1 num_coefficients=1
0.4021 1
contraction shell=H num_primitives=1 num_coefficients=1
0.8207 1
atom=Cd
contraction shell=S num_primitives=1 num_coefficients=1
0.0146 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0121 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0445 1
contraction shell=F num_primitives=1 num_coefficients=1
0.2072 1
contraction shell=G num_primitives=1 num_coefficients=1
0.4694 1
contraction shell=H num_primitives=1 num_coefficients=1
0.9571 1
atom=In
contraction shell=S num_primitives=1 num_coefficients=1
0.0162 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0090 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0244 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0581 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1419 1.00000
atom=Sn
contraction shell=S num_primitives=1 num_coefficients=1
0.0218 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0145 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0336 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0730 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1720 1.00000
atom=Sb
contraction shell=S num_primitives=1 num_coefficients=1
0.0260 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0189 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0400 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0830 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1840 1.00000
atom=Te
contraction shell=S num_primitives=1 num_coefficients=1
0.0296 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0226 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0531 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0931 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2029 1.00000
atom=I
contraction shell=S num_primitives=1 num_coefficients=1
0.0332 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0257 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0585 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1261 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2344 1.00000
atom=Xe
contraction shell=S num_primitives=1 num_coefficients=1
0.0368 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0288 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0639 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1591 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2659 1.00000
atom=Au
contraction shell=S num_primitives=1 num_coefficients=1
0.0167 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0116 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0328 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1323 1
contraction shell=G num_primitives=1 num_coefficients=1
0.3122 1
contraction shell=H num_primitives=1 num_coefficients=1
0.5844 1
atom=Hg
contraction shell=S num_primitives=1 num_coefficients=1
0.0172 1
contraction shell=P num_primitives=1 num_coefficients=1
0.0116 1
contraction shell=D num_primitives=1 num_coefficients=1
0.0401 1
contraction shell=F num_primitives=1 num_coefficients=1
0.1486 1
contraction shell=G num_primitives=1 num_coefficients=1
0.3606 1
contraction shell=H num_primitives=1 num_coefficients=1
0.6541 1
atom=Tl
contraction shell=S num_primitives=1 num_coefficients=1
0.0159 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0081 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0237 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0605 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1527 1.00000
atom=Pb
contraction shell=S num_primitives=1 num_coefficients=1
0.0216 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0137 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0339 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0723 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1746 1.00000
atom=Bi
contraction shell=S num_primitives=1 num_coefficients=1
0.0253 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0183 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0398 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0811 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1800 1.00000
atom=Po
contraction shell=S num_primitives=1 num_coefficients=1
0.0274 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0203 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0487 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.0887 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.1943 1.00000
atom=At
contraction shell=S num_primitives=1 num_coefficients=1
0.0297 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0229 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0542 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1210 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2217 1.00000
atom=Rn
contraction shell=S num_primitives=1 num_coefficients=1
0.0320 1.00000
contraction shell=P num_primitives=1 num_coefficients=1
0.0255 1.00000
contraction shell=D num_primitives=1 num_coefficients=1
0.0597 1.00000
contraction shell=F num_primitives=1 num_coefficients=1
0.1533 1.00000
contraction shell=G num_primitives=1 num_coefficients=1
0.2491 1.00000
