atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.023630 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.084800 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.190000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.360000 1.000000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.048190 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.162600 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.351000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.690600 1.000000
atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
0.006360 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.007560 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.026600 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.055200 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.105000 1.000000
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
0.014390 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.006500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.055400 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.093000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.183400 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.027210 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.018780 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.046600 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.113000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.273000 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.041450 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.032180 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.076600 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.187000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.424000 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.054640 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.044020 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.111000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.245000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.559000 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.069590 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.053480 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.154000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.324000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.714000 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.085940 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.065680 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.207000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.460000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.924000 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.105400 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.081780 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.273000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.689000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.224000 1.000000
atom=Na
contraction shell=S num_primitives=1 num_coefficients=1
0.00503 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.00772 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.02100 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.04530 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.08660 1.000000
atom=Mg
contraction shell=S num_primitives=1 num_coefficients=1
0.01239 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.00706 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.03820 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.07000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.14800 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.01830 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01210 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.02820 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.05820 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.15300 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.02750 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.04350 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.08460 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.21200 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.03540 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02720 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.05940 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.10900 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.25000 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.04280 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03170 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.07480 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.14000 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.29700 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.05190 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03760 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.09520 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.21700 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.37800 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.06100 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.04350 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.11600 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.29400 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.45900 1.0000
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.018475 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.011406 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.02790 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.06550 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.16800 1.0000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.026390 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.018550 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.03970 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.08840 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.21430 1.0000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.032499 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.023698 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.05310 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.11320 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.23900 1.0000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.038152 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.026569 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.06190 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.12400 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.26300 1.0000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.044270 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.030513 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.08290 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.17480 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.31100 1.0000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.050388 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.034457 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.10390 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.22560 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.35900 1.0000
