atom=Sc
contraction shell=S num_primitives=1 num_coefficients=1
0.01110 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01066 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01244 1
contraction shell=F num_primitives=1 num_coefficients=1
0.04063 1
contraction shell=G num_primitives=1 num_coefficients=1
0.09473 1
atom=Ti
contraction shell=S num_primitives=1 num_coefficients=1
0.01173 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01172 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01712 1
contraction shell=F num_primitives=1 num_coefficients=1
0.08069 1
contraction shell=G num_primitives=1 num_coefficients=1
0.20413 1
atom=V
contraction shell=S num_primitives=1 num_coefficients=1
0.01232 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01240 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02240 1
contraction shell=F num_primitives=1 num_coefficients=1
0.12813 1
contraction shell=G num_primitives=1 num_coefficients=1
0.37212 1
atom=Cr
contraction shell=S num_primitives=1 num_coefficients=1
0.01247 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01307 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02498 1
contraction shell=F num_primitives=1 num_coefficients=1
0.17249 1
contraction shell=G num_primitives=1 num_coefficients=1
0.49896 1
atom=Mn
contraction shell=S num_primitives=1 num_coefficients=1
0.01335 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01376 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02853 1
contraction shell=F num_primitives=1 num_coefficients=1
0.21764 1
contraction shell=G num_primitives=1 num_coefficients=1
0.61436 1
atom=Fe
contraction shell=S num_primitives=1 num_coefficients=1
0.01401 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01401 1
contraction shell=D num_primitives=1 num_coefficients=1
0.03216 1
contraction shell=F num_primitives=1 num_coefficients=1
0.26723 1
contraction shell=G num_primitives=1 num_coefficients=1
0.76426 1
atom=Co
contraction shell=S num_primitives=1 num_coefficients=1
0.01459 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01520 1
contraction shell=D num_primitives=1 num_coefficients=1
0.03598 1
contraction shell=F num_primitives=1 num_coefficients=1
0.32041 1
contraction shell=G num_primitives=1 num_coefficients=1
0.92816 1
atom=Ni
contraction shell=S num_primitives=1 num_coefficients=1
0.01516 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01494 1
contraction shell=D num_primitives=1 num_coefficients=1
0.03999 1
contraction shell=F num_primitives=1 num_coefficients=1
0.37725 1
contraction shell=G num_primitives=1 num_coefficients=1
1.17446 1
atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.01572 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01538 1
contraction shell=D num_primitives=1 num_coefficients=1
0.06489 1
contraction shell=F num_primitives=1 num_coefficients=1
0.45165 1
contraction shell=G num_primitives=1 num_coefficients=1
1.40556 1
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.01623 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01582 1
contraction shell=D num_primitives=1 num_coefficients=1
0.08897 1
contraction shell=F num_primitives=1 num_coefficients=1
0.53654 1
contraction shell=G num_primitives=1 num_coefficients=1
1.75126 1
