atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.02210 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01460 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0357 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.08580 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.03300 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02370 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0551 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.12500 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.04090 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03070 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.07750 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.16500 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.04970 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03510 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.101 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.21800 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.05910 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.04190 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.130 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.31200 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.06850 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.04870 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.155 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.40600 1.0000
