atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.025260 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.102000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.247000 1.000000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.051380 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.199300 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.459200 1.000000
atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
0.007600 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.009100 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.037100 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.081600 1.000000
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
0.015030 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.007060 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.065400 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.153300 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.029140 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.020960 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.060400 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.163000 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.044020 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.035690 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.100000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.268000 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.057600 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.049100 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.151000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.364000 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.073760 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.059740 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.214000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.500000 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.091580 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.073610 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.292000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.724000 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.113300 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.091750 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.386000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.084000 1.000000
atom=Na
contraction shell=S num_primitives=1 num_coefficients=1
0.006650 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.007000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.022300 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.071400 1.000000
atom=Mg
contraction shell=S num_primitives=1 num_coefficients=1
0.012900 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.007450 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.046800 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.094000 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.02210 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01460 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.03560 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.08580 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.03300 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02370 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.05560 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.12500 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.04090 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03070 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.07750 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.16500 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.04970 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03510 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.10100 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.21800 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.05910 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.04190 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.13500 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.31200 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.06850 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.04870 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.16900 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.40600 1.0000
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.014398 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.01930 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.03870 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.09800 1.0000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.027370 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.021368 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.05280 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.13230 1.0000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.033407 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.026799 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.07000 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.16900 1.0000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.039201 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.030251 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.08370 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.18800 1.0000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.045593 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.035142 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.10470 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.25800 1.0000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.051985 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.040033 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.12570 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.32800 1.0000
