atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.029740 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.141000 1.000000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.072550 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.247300 1.000000
atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
0.008640 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.005790 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.072500 1.000000
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
0.018770 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.008500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.074000 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.031050 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.023780 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.090400 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.046900 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.040410 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.151000 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.061240 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.056110 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.230000 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.078960 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.068560 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.332000 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.098630 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.085020 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.464000 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.123000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.106400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.631000 1.000000
atom=Na
contraction shell=S num_primitives=1 num_coefficients=1
0.00725 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.00633 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.04680 1.000000
atom=Mg
contraction shell=S num_primitives=1 num_coefficients=1
0.01488 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.00935 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.05950 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.02310 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01530 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.05350 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.03320 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.08230 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.04170 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03430 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.11300 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.05070 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03990 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.15200 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.06080 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.04660 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.19600 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.07090 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.05330 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.24000 1.0000
atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.024348 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.015164 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.05370 1.0000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.033961 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.023945 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.07710 1.0000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.041152 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.031268 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.10780 1.0000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.048747 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.035492 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.12830 1.0000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.056946 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.041049 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.17190 1.0000
atom=Kr
contraction shell=S num_primitives=1 num_coefficients=1
0.065145 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.046606 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.21550 1.0000
