atom=H
contraction shell=S num_primitives=8 num_coefficients=1
402.000 0.000279
60.2400 0.002165
13.7300 0.011201
3.90500 0.044878
1.28300 0.142299
0.46550 0.330979
0.18110 0.436269
0.07279 0.176440
contraction shell=S num_primitives=1 num_coefficients=1
2.6799 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.0787 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.4342 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.1748 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.0704 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.0169 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.4339 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.3502 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.3308 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.5286 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.2100 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0659 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.3376 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.9050 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.8367 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.3675 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1240 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.8943 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.7087 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.7497 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.2394 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
3.6343 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.5186 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.4378 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
2.2538 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
0.6399 1.000000
