atom=Sc
contraction shell=S num_primitives=1 num_coefficients=1
0.14496 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.18964 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.33836 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.04169 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.09750 1.0
atom=Ti
contraction shell=S num_primitives=1 num_coefficients=1
0.01173 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01176 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.01726 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.08266 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.21148 1.0
atom=V
contraction shell=S num_primitives=1 num_coefficients=1
0.01232 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01244 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.02256 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.13112 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.38465 1.0
atom=Cr
contraction shell=S num_primitives=1 num_coefficients=1
0.01247 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01307 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.02517 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.17636 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.51329 1.0
atom=Mn
contraction shell=S num_primitives=1 num_coefficients=1
0.01335 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01380 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02875 1
contraction shell=F num_primitives=1 num_coefficients=1
0.22260 1
contraction shell=G num_primitives=1 num_coefficients=1
0.63213 1
atom=Fe
contraction shell=S num_primitives=1 num_coefficients=1
0.01401 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01407 1
contraction shell=D num_primitives=1 num_coefficients=1
0.03243 1
contraction shell=F num_primitives=1 num_coefficients=1
0.27490 1
contraction shell=G num_primitives=1 num_coefficients=1
0.78716 1
atom=Co
contraction shell=S num_primitives=1 num_coefficients=1
0.01459 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01525 1
contraction shell=D num_primitives=1 num_coefficients=1
0.03625 1
contraction shell=F num_primitives=1 num_coefficients=1
0.32715 1
contraction shell=G num_primitives=1 num_coefficients=1
0.95814 1
atom=Ni
contraction shell=S num_primitives=1 num_coefficients=1
0.01516 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01502 1
contraction shell=D num_primitives=1 num_coefficients=1
0.04067 1
contraction shell=F num_primitives=1 num_coefficients=1
0.40830 1
contraction shell=G num_primitives=1 num_coefficients=1
1.20485 1
atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.01572 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01545 1
contraction shell=D num_primitives=1 num_coefficients=1
0.06591 1
contraction shell=F num_primitives=1 num_coefficients=1
0.46172 1
contraction shell=G num_primitives=1 num_coefficients=1
1.45979 1
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.01623 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01592 1
contraction shell=D num_primitives=1 num_coefficients=1
0.09049 1
contraction shell=F num_primitives=1 num_coefficients=1
0.54861 1
contraction shell=G num_primitives=1 num_coefficients=1
1.82933 1
