atom=Sc
contraction shell=S num_primitives=1 num_coefficients=1
0.01047 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01012 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.00952 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.03128 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.07236 1.0
contraction shell=H num_primitives=1 num_coefficients=1
0.12264 1.0
atom=Ti
contraction shell=S num_primitives=1 num_coefficients=1
0.01110 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01103 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.01279 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.05541 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.12566 1.0
contraction shell=H num_primitives=1 num_coefficients=1
0.27242 1.0
atom=V
contraction shell=S num_primitives=1 num_coefficients=1
0.01172 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01166 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01630 1
contraction shell=F num_primitives=1 num_coefficients=1
0.08185 1
contraction shell=G num_primitives=1 num_coefficients=1
0.19339 1
contraction shell=H num_primitives=1 num_coefficients=1
0.47119 1
atom=Cr
contraction shell=S num_primitives=1 num_coefficients=1
0.01157 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01233 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01778 1
contraction shell=F num_primitives=1 num_coefficients=1
0.10373 1
contraction shell=G num_primitives=1 num_coefficients=1
0.24545 1
contraction shell=H num_primitives=1 num_coefficients=1
0.63292 1
atom=Mn
contraction shell=S num_primitives=1 num_coefficients=1
0.01280 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01287 1
contraction shell=D num_primitives=1 num_coefficients=1
0.01978 1
contraction shell=F num_primitives=1 num_coefficients=1
0.12829 1
contraction shell=G num_primitives=1 num_coefficients=1
0.31841 1
contraction shell=H num_primitives=1 num_coefficients=1
0.77671 1
atom=Fe
contraction shell=S num_primitives=1 num_coefficients=1
0.01348 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01305 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02205 1
contraction shell=F num_primitives=1 num_coefficients=1
0.15514 1
contraction shell=G num_primitives=1 num_coefficients=1
0.40738 1
contraction shell=H num_primitives=1 num_coefficients=1
0.95878 1
atom=Co
contraction shell=S num_primitives=1 num_coefficients=1
0.01409 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01421 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02432 1
contraction shell=F num_primitives=1 num_coefficients=1
0.18416 1
contraction shell=G num_primitives=1 num_coefficients=1
0.49631 1
contraction shell=H num_primitives=1 num_coefficients=1
1.15791 1
atom=Ni
contraction shell=S num_primitives=1 num_coefficients=1
0.01467 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01388 1
contraction shell=D num_primitives=1 num_coefficients=1
0.02691 1
contraction shell=F num_primitives=1 num_coefficients=1
0.22650 1
contraction shell=G num_primitives=1 num_coefficients=1
0.62370 1
contraction shell=H num_primitives=1 num_coefficients=1
1.44860 1
atom=Cu
contraction shell=S num_primitives=1 num_coefficients=1
0.01524 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01426 1
contraction shell=D num_primitives=1 num_coefficients=1
0.04614 1
contraction shell=F num_primitives=1 num_coefficients=1
0.25747 1
contraction shell=G num_primitives=1 num_coefficients=1
0.73212 1
contraction shell=H num_primitives=1 num_coefficients=1
1.67681 1
atom=Zn
contraction shell=S num_primitives=1 num_coefficients=1
0.01576 1
contraction shell=P num_primitives=1 num_coefficients=1
0.01472 1
contraction shell=D num_primitives=1 num_coefficients=1
0.06598 1
contraction shell=F num_primitives=1 num_coefficients=1
0.29949 1
contraction shell=G num_primitives=1 num_coefficients=1
0.86736 1
contraction shell=H num_primitives=1 num_coefficients=1
2.02734 1
