atom=H
contraction shell=S num_primitives=9 num_coefficients=1
884.1687 0.000104
132.3019 0.000812
30.10101 0.004250
8.521526 0.017618
2.777332 0.060663
1.000995 0.170162
0.388919 0.349649
0.159594 0.402808
0.066851 0.138698
contraction shell=S num_primitives=1 num_coefficients=1
4.96826 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.084332 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.874439 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.366853 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.153906 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.064568 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.01596 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.553545 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.120174 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.573705 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.082315 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.455144 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.191401 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.061711 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.469935 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.974713 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.367698 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.628833 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.289122 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.10317 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.923876 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.55024 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.590661 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.712685 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.23201 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
4.164494 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.843627 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.816176 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.295566 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
4.670296 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
2.047084 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
0.59445 1.000000
contraction shell=I num_primitives=1 num_coefficients=1
2.326066 1.000000
contraction shell=I num_primitives=1 num_coefficients=1
0.73138 1.000000
