atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.02310 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01530 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0552 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.03320 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0840 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.04170 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03430 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.116 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.05070 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.03990 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.155 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.06080 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.04660 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.198 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.07090 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.05330 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.238 1.0000
