atom=Ga
contraction shell=D num_primitives=1 num_coefficients=1
0.141000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.167000 1.000000
atom=Ge
contraction shell=D num_primitives=1 num_coefficients=1
0.202000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.267000 1.000000
atom=As
contraction shell=D num_primitives=1 num_coefficients=1
0.273000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.372000 1.000000
atom=Se
contraction shell=D num_primitives=1 num_coefficients=1
0.315000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.400000 1.000000
atom=Br
contraction shell=D num_primitives=1 num_coefficients=1
0.338000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.401000 1.000000
atom=Kr
contraction shell=D num_primitives=1 num_coefficients=1
0.318000 1.000000
contraction shell=F num_primitives=1 num_coefficients=12
0.401000 1.000000 ! Binning and Curtiss did not give an f exponent for
