atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
0.906000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.242000 1.000000
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
1.860000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.163000 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
3.066000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.940000 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
4.530000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.55700 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
6.233000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
19.97700 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
8.215000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
26.05600 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
10.42600 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
32.83000 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
12.85400 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
40.18400 1.000000
atom=Na
contraction shell=S num_primitives=1 num_coefficients=1
0.704000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.761000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.949000 1.000000
atom=Mg
contraction shell=S num_primitives=1 num_coefficients=1
3.422000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.279000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.704000 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
4.030 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.529 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.725 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
4.959 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.998 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.806 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
5.977 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.524 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.020 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
7.083 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.089 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.363 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
8.273 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.697 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.844 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
9.548 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.361 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.459 1.000000
atom=Ca
contraction shell=S num_primitives=1 num_coefficients=1
1.114300 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.510100 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.374300 1.000000
