atom=H
contraction shell=S num_primitives=1 num_coefficients=1
33.87000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
5.09500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.15900 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.32580 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.10270 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.40700 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.38800 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.05700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.02568 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.09700 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.09700 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.26425 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.05135 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.19400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.19400 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.52850 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.70350 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.77600 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.11400 1.0
contraction shell=F num_primitives=1 num_coefficients=1
2.11400 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.48480 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.05700 1.0
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
234.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
35.16000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
7.98900 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.21200 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.66690 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.20890 1.0
contraction shell=P num_primitives=1 num_coefficients=1
3.04400 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.75800 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.96500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.05223 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.18950 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.18950 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.49125 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.10445 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.37900 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.37900 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.98250 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.52200 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.51600 1.0
contraction shell=D num_primitives=1 num_coefficients=1
3.93000 1.0
contraction shell=F num_primitives=1 num_coefficients=1
3.93000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.87890 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.96500 1.0
atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
5988.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
898.90000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
205.90000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
59.24000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
19.87000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
7.40600 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.93000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.18900 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.47980 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.07509 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.02832 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.01416 1.0
contraction shell=P num_primitives=1 num_coefficients=1
3.26600 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.65110 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.16960 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.05578 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.02050 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.18740 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.08010 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.18290 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01025 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.04005 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.16020 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.36580 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.36580 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.22538 1.0
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
6863.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1030.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
234.70000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
66.56000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
21.69000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
7.73400 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.91600 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.13000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.25770 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.11010 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.04409 1.0
contraction shell=P num_primitives=1 num_coefficients=1
7.43600 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.57700 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.43520 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.14380 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.04994 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.34800 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.18030 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.32500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.02204 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.02497 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.09015 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.36060 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.65000 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.65000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.57900 1.0
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
5473.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
820.90000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
186.80000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
52.83000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
17.08000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
5.99900 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.20800 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.58790 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.24150 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.08610 1.0
contraction shell=P num_primitives=1 num_coefficients=1
12.05000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.61300 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.74750 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.23850 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.07698 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.66100 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.19900 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.49000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.04305 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.03849 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.09950 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.39800 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.98000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.98600 1.0
contraction shell=G num_primitives=1 num_coefficients=1
0.98000 1.0
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
8236.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1235.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
280.80000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
79.27000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
25.59000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
8.99700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
3.31900 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.90590 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.36430 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.12850 1.0
contraction shell=P num_primitives=1 num_coefficients=1
18.71000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
4.13300 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.20000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.38270 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.12090 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.09700 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.31800 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.76100 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.06425 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.06045 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.15900 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.63600 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.52200 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.58270 1.0
contraction shell=G num_primitives=1 num_coefficients=1
1.52200 1.0
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
11420.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1712.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
389.30000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
110.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
35.57000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
12.54000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
4.64400 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.29300 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.51180 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.17870 1.0
contraction shell=P num_primitives=1 num_coefficients=1
26.63000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
5.94800 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.74200 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.55500 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.17250 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.65400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.46900 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.09300 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.08935 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.08625 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.23450 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.93800 1.0
contraction shell=F num_primitives=1 num_coefficients=1
2.18600 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.29700 1.0
contraction shell=G num_primitives=1 num_coefficients=1
2.18600 1.0
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
15330.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2299.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
522.40000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
147.30000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
47.55000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
16.76000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
6.20700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.75200 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.68820 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.23840 1.0
contraction shell=P num_primitives=1 num_coefficients=1
34.46000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
7.74900 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.28000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.71560 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.21400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.31400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.64500 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.42800 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.11920 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.10700 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.32250 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.29000 1.0
contraction shell=F num_primitives=1 num_coefficients=1
2.85600 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.99560 1.0
contraction shell=G num_primitives=1 num_coefficients=1
2.85600 1.0
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
19500.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2923.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
664.50000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
187.50000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
60.62000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
21.42000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
7.95000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.25700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.88150 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.30410 1.0
contraction shell=P num_primitives=1 num_coefficients=1
43.88000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
9.92600 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.93000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.91320 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.26720 1.0
contraction shell=D num_primitives=1 num_coefficients=1
3.10700 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.85500 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.91700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.15205 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.13360 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.42750 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.71000 1.0
contraction shell=F num_primitives=1 num_coefficients=1
3.83400 1.0
contraction shell=G num_primitives=1 num_coefficients=1
3.83400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
3.84320 1.0
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
24350.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
3650.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
829.60000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
234.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
75.61000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
26.73000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
9.92700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.83600 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.10200 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.37820 1.0
contraction shell=P num_primitives=1 num_coefficients=1
54.70000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
12.43000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
3.67900 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.14300 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.33000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
4.01400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.09600 1.0
contraction shell=F num_primitives=1 num_coefficients=1
2.54400 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.18910 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.16500 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.54800 1.0
contraction shell=F num_primitives=1 num_coefficients=1
2.19200 1.0
contraction shell=F num_primitives=1 num_coefficients=1
5.08800 1.0
contraction shell=G num_primitives=1 num_coefficients=1
5.08800 1.0
contraction shell=D num_primitives=1 num_coefficients=1
4.82200 1.0
