atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
7.497 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.275 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.199 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.537 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.634 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.645 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.687 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
9.1570 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.619 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.446 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.514 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.659 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.3050 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.0020 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
11.006 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.003 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.071 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.698 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
12.865 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.0430 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
8.4650 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
12.930 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.410 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.101 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.105 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.243 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.842 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
10.053 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
15.078 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.871 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.482 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.671 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
17.944 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.7550 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
11.780 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
17.410 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.376 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.019 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.306 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
20.705 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.679 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
13.675 1.000000
