atom=O
contraction shell=S num_primitives=1 num_coefficients=1
348.4406 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
175.3001 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
88.19334 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
44.36999 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
22.32250 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
363.9568 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
163.0141 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
73.01309 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
32.70214 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.64710 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
253.9252 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
109.6239 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
47.32656 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
20.43170 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
138.2648 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
49.00349 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
17.36770 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
82.36451 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
23.67640 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
62.71532 1.000000
