atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
9.729 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
4.874 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.442 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.009 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.519 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.040 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.813 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.630 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.140 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
9.838 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.515 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
6.894 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
12.175 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
6.1930 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.1500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
12.615 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.7310 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.6040 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.136 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.4200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.8770 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
11.910 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.2980 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
8.5810 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
14.833 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
7.634 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.929 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
15.771 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.136 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.229 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.548 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.267 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.647 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
14.206 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.149 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
10.450 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
17.596 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
9.256 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
4.869 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
17.864 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.150 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.718 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
27.378 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.873 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.318 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
16.582 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.032 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
12.487 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
20.747 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
10.885 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
5.7110 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
20.667 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.3390 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.2200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
32.206 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
12.882 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.1530 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
19.114 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.9530 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
14.781 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
24.044 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
12.715 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
6.724 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
23.633 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.655 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.804 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
37.411 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.025 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.034 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
21.869 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.958 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
17.244 1.000000
