atom=B
contraction shell=S num_primitives=1 num_coefficients=1
3.7680 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
10.414 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
28.788 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.8470 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.925 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
36.971 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.7180 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
16.574 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.6920 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
5.5840 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
15.109 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
40.881 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.9960 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.057 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
54.382 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.8880 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
22.804 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.1160 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
7.8290 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
20.735 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
54.917 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.5540 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
25.190 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
74.185 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.6930 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
31.167 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
8.9720 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
10.478 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
27.314 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
71.206 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.161 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
32.459 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
94.398 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.469 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
39.239 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
12.163 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
13.454 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
34.581 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
88.880 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.230 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
40.862 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
117.339 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
49.610 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
16.168 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
16.923 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
42.923 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
108.870 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
17.724 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
50.291 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
142.701 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.104 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
61.555 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
20.877 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
1.794 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.916 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
8.549 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.049 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.468 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.740 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.379 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.887 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.960 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.463 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.814 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.645 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
2.420 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
5.122 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
10.842 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.562 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.468 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.670 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.970 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.472 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.195 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.857 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
8.537 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.934 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
3.113 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
6.434 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
13.298 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.112 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.615 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.060 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.590 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.119 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.566 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.310 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
10.518 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.328 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
3.807 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
7.780 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
15.901 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.522 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.539 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
16.139 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.116 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.524 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.323 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.801 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
12.703 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.739 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
4.570 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
9.277 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
18.831 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.932 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.492 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.338 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.799 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.312 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
27.991 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.389 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
15.188 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
3.239 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
5.386 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
10.867 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
21.926 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.411 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.556 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
20.702 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.530 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
12.215 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
32.933 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.030 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
17.874 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
3.816 1.000000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
6.6640 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
13.563 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
27.605 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.1200 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.068 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
23.928 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.2930 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.8040 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.065 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.1130 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.2890 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
13.241 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.3320 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
9.2410 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
2.5630 1.000000
