atom=B
contraction shell=S num_primitives=1 num_coefficients=1
127.620 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
63.651 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
31.746 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
15.833 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
7.897 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
144.211 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
63.698 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
28.135 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
12.427 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.489 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
100.398 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
43.163 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
18.557 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.978 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
56.093 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
20.309 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.353 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
43.016 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
14.469 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
29.555 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
183.076 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
91.998 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
46.230 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
23.231 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
11.674 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
206.567 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
92.589 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
41.501 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.602 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.338 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
145.524 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
62.916 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
27.201 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.760 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
78.565 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
28.059 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
10.021 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
55.145 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
17.607 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
40.710 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
246.262 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
124.187 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
62.626 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
31.581 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
15.926 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
270.142 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
123.465 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
56.428 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
25.790 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.787 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
199.920 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
87.111 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
37.957 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
16.539 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
105.346 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
37.530 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
13.370 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
67.188 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
20.360 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
52.050 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
317.096 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
160.393 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
81.129 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
41.037 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
20.757 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
358.911 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
161.818 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
72.957 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
32.893 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.830 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
250.830 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
108.163 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
46.642 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
20.113 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
136.111 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
48.855 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
17.536 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
81.628 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
24.065 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
62.850 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
397.544 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
201.594 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
102.228 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
51.840 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
26.288 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
446.570 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
201.339 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
90.775 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
40.927 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.452 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
313.731 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
135.404 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
58.439 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
25.222 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
177.220 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
64.350 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
23.366 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
99.384 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
29.517 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
67.820 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
526.1367 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
264.9976 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
133.4704 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
67.22462 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
33.85880 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
558.8741 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
250.2470 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
112.0531 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
50.17399 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
22.46640 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
392.7164 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
169.5564 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
73.20647 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
31.60710 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
224.9657 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
82.45185 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
30.21930 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
119.8449 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
33.52550 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
50.90847 1.000000
