atom=H
contraction shell=S num_primitives=1 num_coefficients=1
13.01000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
6.50500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.96200 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.98100 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.44460 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.22230 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.12200 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.06100 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.03050 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.40660 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.45400 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.72700 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.36350 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.24400 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.18175 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.45400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.72700 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.18175 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.36350 1.0
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
38.36000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
5.77000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.24000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.29760 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.27500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.07440 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.62000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.88500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
19.18000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.14880 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.31875 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.31875 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.63750 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.63750 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.59520 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.55000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.55000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
7.01000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.27500 1.0
atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
1469.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
220.50000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
50.26000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
14.24000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
4.58100 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.58000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.56400 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.07345 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.02805 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.53400 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.27490 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.07362 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.02403 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.12390 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.01402 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.01201 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.04806 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.24780 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.24780 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.34852 1.0
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
2940.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
441.20000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
100.50000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
28.43000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
9.16900 1.0
contraction shell=S num_primitives=1 num_coefficients=1
3.19600 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.15900 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.18110 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.05890 1.0
contraction shell=P num_primitives=1 num_coefficients=1
3.61900 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.71100 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.19510 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.06018 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.23800 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.02945 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.03009 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.12036 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.47600 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.47600 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.90610 1.0
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
4570.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
685.90000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
156.50000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
44.47000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
14.48000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
5.13100 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.89800 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.33290 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.10430 1.0
contraction shell=P num_primitives=1 num_coefficients=1
6.00100 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.24100 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.33640 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.09538 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.34300 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.05215 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.04769 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.19076 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.68600 1.0
contraction shell=F num_primitives=1 num_coefficients=1
0.68600 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.57740 1.0
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
6665.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1000.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
228.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
64.71000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
21.06000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
7.49500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2.79700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.52150 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.15960 1.0
contraction shell=P num_primitives=1 num_coefficients=1
9.43900 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.00200 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.54560 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.15170 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.55000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.07980 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.07585 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.30340 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.10000 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.10000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.54760 1.0
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
9046.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1357.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
309.30000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
87.73000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
28.56000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
10.21000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
3.83800 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.74660 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.22480 1.0
contraction shell=P num_primitives=1 num_coefficients=1
13.55000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
2.91700 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.79730 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.21850 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.81700 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.11240 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.10925 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.43700 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.63400 1.0
contraction shell=F num_primitives=1 num_coefficients=1
1.63400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
3.71430 1.0
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
11720.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1759.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
400.80000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
113.70000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
37.03000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
13.27000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
5.02500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.01300 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.30230 1.0
contraction shell=P num_primitives=1 num_coefficients=1
17.70000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
3.85400 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.04600 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.27530 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.18500 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.15115 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.13765 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.55060 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.37000 1.0
contraction shell=F num_primitives=1 num_coefficients=1
2.37000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
4.90000 1.0
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
14710.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2207.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
502.80000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
142.60000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
46.47000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
16.70000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
6.35600 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.31600 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.38970 1.0
contraction shell=P num_primitives=1 num_coefficients=1
22.67000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
4.97700 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.34700 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.34710 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.64000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.19485 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.17355 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.69420 1.0
contraction shell=D num_primitives=1 num_coefficients=1
3.28000 1.0
contraction shell=F num_primitives=1 num_coefficients=1
3.28000 1.0
contraction shell=D num_primitives=1 num_coefficients=1
6.32400 1.0
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
17880.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
2683.00000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
611.50000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
173.50000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
56.64000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
20.42000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
7.81000 1.0
contraction shell=S num_primitives=1 num_coefficients=1
1.65300 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.48690 1.0
contraction shell=P num_primitives=1 num_coefficients=1
28.39000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
6.27000 1.0
contraction shell=P num_primitives=1 num_coefficients=1
1.69500 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.43170 1.0
contraction shell=D num_primitives=1 num_coefficients=1
2.20200 1.0
contraction shell=S num_primitives=1 num_coefficients=1
0.24345 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.21585 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.86340 1.0
contraction shell=D num_primitives=1 num_coefficients=1
4.40400 1.0
contraction shell=F num_primitives=1 num_coefficients=1
4.40400 1.0
contraction shell=D num_primitives=1 num_coefficients=1
7.96500 1.0
