atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
1.9740 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.6830 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.3200 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.8750 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.9120 1.000000
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
4.6040 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.6170 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.497 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.7870 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.1830 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
2.9400 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
8.3110 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.0160 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
22.891 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
13.015 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
4.2920 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
11.876 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.7780 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
33.190 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.839 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
5.9520 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
16.201 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.871 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
44.849 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.200 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
7.8450 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
21.032 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
15.159 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
57.437 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.858 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
9.8120 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
25.943 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.756 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
71.348 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.108 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
12.083 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
31.947 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
22.827 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
87.017 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.168 1.000000
atom=Na
contraction shell=S num_primitives=1 num_coefficients=1
4.1890 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.6260 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.5690 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.5120 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.4040 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.5300 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.4650 1.000000
atom=Mg
contraction shell=S num_primitives=1 num_coefficients=1
17.516 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.8700 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
20.297 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.1050 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.0290 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.1210 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.5300 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
7.488 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.272 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.202 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.548 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.634 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.646 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.686 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
9.164 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.621 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.458 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.517 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.671 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.308 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.001 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
10.978 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.006 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.084 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.701 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
12.891 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.056 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
8.462 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
12.928 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.413 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.114 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.106 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.254 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.845 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
10.052 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
15.064 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.874 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.480 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.668 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
17.957 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.7600 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
11.779 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
17.362 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.378 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.019 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.307 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
20.706 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.681 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
13.674 1.000000
atom=Ca
contraction shell=S num_primitives=1 num_coefficients=1
2.063000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.409800 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.880600 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.534700 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.277500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.127000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.390900 1.000000
