atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
5.6140 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.8600 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.6160 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.7850 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.5930 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.6870 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.602 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.0660 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.6830 1.000000
atom=Be
contraction shell=S num_primitives=1 num_coefficients=1
21.726 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
7.8660 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.8480 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
30.898 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.365 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.4770 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
30.390 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.0920 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
12.482 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
4.8640 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
13.288 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
36.304 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.4890 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
16.302 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
48.418 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.6400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
24.462 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
18.794 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
7.2160 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
19.570 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
53.073 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.1820 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
24.186 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
71.494 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.6560 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
33.213 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
24.694 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
9.8620 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
26.627 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
71.894 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.320 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
33.349 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
98.245 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.828 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
45.218 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
28.364 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
12.974 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
34.900 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
93.881 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.475 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
42.730 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
126.14 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.927 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
57.544 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
26.483 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
16.319 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
43.784 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
117.472 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.119 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
53.505 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
158.001 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
18.943 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
72.798 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
25.161 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
20.180 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
54.042 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
144.725 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
22.222 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
65.622 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
193.780 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.613 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
90.107 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
28.830 1.000000
atom=Na
contraction shell=S num_primitives=1 num_coefficients=1
24.282 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
4.8740 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.9780 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.4660 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.6890 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.6380 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.6060 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.1370 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.1440 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.2580 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.1730 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
4.0970 1.000000
atom=Mg
contraction shell=S num_primitives=1 num_coefficients=1
23.243 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
9.5610 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.9330 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
39.536 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
12.778 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.1300 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
12.533 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.6770 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.7450 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.8760 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.8050 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
5.3940 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
9.729 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
4.870 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.437 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.514 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.038 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.835 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.637 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.142 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
9.853 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.525 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
6.894 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
12.164 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
6.187 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.147 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
12.646 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.747 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.612 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.015 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.401 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.881 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
11.925 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.304 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
8.577 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
14.831 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
7.640 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
3.935 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
15.523 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.073 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.223 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.417 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.250 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.654 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
14.207 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.161 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
10.448 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
17.599 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
9.186 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
4.795 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.127 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.219 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.726 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
27.417 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.893 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.319 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
16.535 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.008 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
12.518 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
20.689 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
10.880 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
5.722 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
20.784 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.379 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.232 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
32.255 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
12.888 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.149 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
19.107 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.950 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
14.782 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
24.024 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
12.706 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
6.720 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
23.627 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.654 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.804 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
37.364 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.013 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.032 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
21.884 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.968 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
17.243 1.000000
atom=Ca
contraction shell=S num_primitives=1 num_coefficients=1
3.2818 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
1.5643 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.7456 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.3392 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.6309 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.7966 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.3287 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.6458 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.8137 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.2297 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.2035 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.5908 1.000000
