atom=B
contraction shell=S num_primitives=1 num_coefficients=1
2.463000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.566000 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
3.339000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.235000 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
4.320000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.23900 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
5.459000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
13.32000 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
6.724000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
16.80300 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
8.116000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
20.65800 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
3.599000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.928000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.792000 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
4.499000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.388000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.277000 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
5.474000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.939000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.760000 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
6.501000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.503000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.211000 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
7.591000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.092000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.701000 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
8.742000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.711000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.251000 1.000000
