atom=B
contraction shell=S num_primitives=1 num_coefficients=1
6.411 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
14.521 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
32.890 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
74.496 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.172 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
13.225 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
33.816 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
86.467 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.066 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.721 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
55.042 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
9.994 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
33.090 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
24.020 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
9.185 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
20.795 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
47.080 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
106.588 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.668 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
19.484 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
49.510 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
125.804 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.009 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
28.065 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
78.695 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
11.693 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
41.569 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
32.780 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
12.275 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
27.827 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
63.085 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
143.013 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.7600 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
27.1800 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
68.656 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
173.425 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.053 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
39.081 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
108.685 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
14.357 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
52.690 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
41.120 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
15.645 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
35.874 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
82.259 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
188.62 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.049 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
35.446 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
89.429 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
225.63 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
16.703 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
47.320 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
134.056 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
17.354 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
65.546 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
48.578 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
19.876 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
44.880 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
101.339 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
228.824 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
17.306 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
43.663 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
110.162 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
277.938 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
21.731 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
60.955 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
170.890 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
22.337 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
82.290 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
49.727 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
24.313 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
54.680 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
122.975 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
276.571 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
21.309 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
53.720 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
135.428 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
341.414 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
27.044 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
75.750 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
212.176 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
28.029 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
102.586 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
38.794 1.000000
atom=Na
contraction shell=S num_primitives=1 num_coefficients=1
157.489 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
27.927 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
4.9520 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
0.8780 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.8690 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.4140 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.9740 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.8830 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.401 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.1840 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.6560 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.1400 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
10.524 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.4050 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.8440 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
7.3260 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.7270 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
5.1330 1.000000
atom=Mg
contraction shell=S num_primitives=1 num_coefficients=1
14.396 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
8.1290 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
4.5900 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
2.5920 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
67.773 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
24.887 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
9.1390 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.3560 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
24.823 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.820 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.6290 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.3030 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
13.000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.4710 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.3030 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
9.3890 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
3.5300 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
6.7210 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
30.240 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.249 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.7142 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.163 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
15.641 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.527 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.724 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
11.830 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
4.502 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
8.508 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
39.934 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.483 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.505 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.638 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
18.964 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.956 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.338 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
14.504 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
5.581 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
10.536 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
48.483 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.878 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.760 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.792 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
22.920 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
9.683 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.091 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
17.322 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
6.717 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
12.811 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
56.694 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
28.070 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
13.898 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.881 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
26.382 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
11.072 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.647 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
20.346 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
7.908 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
15.306 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
65.837 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
32.687 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
16.228 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.057 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
30.691 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
12.884 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.409 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
23.446 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
9.121 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
18.066 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
76.808 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
38.737 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
19.537 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.853 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
35.873 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
15.140 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.390 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
26.560 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
10.306 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
21.104 1.000000
atom=Ca
contraction shell=D num_primitives=1 num_coefficients=1
5.6203 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.2886 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.9242 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.1259 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.6792 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.7433 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.6083 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.3770 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.1626 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
1.9816 1.000000
