atom=B
contraction shell=S num_primitives=1 num_coefficients=1
5.8140 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
12.894 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
28.595 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
63.419 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.9740 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.272 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
26.548 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
68.613 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.9550 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.671 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
43.437 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.2920 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
20.450 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
4.3880 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
7.9670 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
17.452 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
38.226 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
83.731 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.0800 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
15.358 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
38.799 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
98.017 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.5910 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
21.419 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
60.439 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.6980 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
24.398 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
7.3110 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
10.422 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
22.596 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
48.993 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
106.226 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.7660 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
21.676 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
53.600 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
132.544 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.016 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
29.806 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
80.643 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
9.4860 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
30.752 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
10.835 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
12.941 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
28.200 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
61.449 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
133.900 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
11.560 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
28.321 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
69.387 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
169.998 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
14.008 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
37.245 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
99.026 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
12.653 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
38.737 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
14.886 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
16.249 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
35.033 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
75.531 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
162.845 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.547 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
35.380 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
86.051 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
209.293 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
18.333 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
47.634 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
123.771 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
16.646 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
49.413 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
19.609 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
19.856 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
42.541 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
91.139 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
195.256 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
18.093 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
43.469 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
104.438 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
250.919 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.115 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
58.983 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
150.508 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
21.460 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
62.368 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
24.973 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
2.589 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.436 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.415 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
23.973 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.502 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.974 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
10.513 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
1.746 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
9.006 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
1.830 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
2.734 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
6.057 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
13.420 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
29.732 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.945 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
5.101 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
13.381 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.161 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
11.435 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
2.225 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
3.535 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.759 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
17.031 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
37.386 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.504 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
6.527 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
17.010 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
2.654 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
14.134 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
2.704 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
4.490 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.713 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
21.013 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
45.458 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.998 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
7.837 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
20.485 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
3.154 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
17.101 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
3.231 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
5.731 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
12.152 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
25.770 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
54.649 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.639 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
9.495 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
24.774 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
3.756 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
20.368 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
3.836 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
6.251 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
13.575 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
29.482 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
64.029 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
4.417 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
11.460 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
29.736 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
4.427 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
23.903 1.000000
contraction shell=H num_primitives=1 num_coefficients=1
4.518 1.000000
