atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
4.032000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.529000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.726000 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
4.960000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.998000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.807000 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
5.980000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.524000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.020000 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
7.082000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.089000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
8.363000 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
8.273000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.697000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.844000 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
9.549000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.361000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.46000 1.000000
