atom=B
contraction shell=S num_primitives=1 num_coefficients=1
2.454000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
6.430000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.498000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
14.37200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.029000 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
3.474000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
8.828000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.442000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
21.55200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.950000 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
4.733000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
11.80700 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.743000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
29.81800 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.352000 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
6.245000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
15.38100 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
10.21600 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
38.48400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
10.23800 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
7.940000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
19.36400 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
13.06900 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
48.32500 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
13.64400 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
9.883000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
23.82900 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
16.27500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
59.24200 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
17.52800 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.995000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
6.562000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
1.811000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
4.871000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.358000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
5.487000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.470000 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
1.336000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
8.252000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.311000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
5.936000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
1.814000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
7.203000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
1.763000 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
1.730000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
10.06900 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.401000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.090000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.328000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
9.097000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.122000 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
2.120000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
11.92000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
2.659000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
6.647000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
2.864000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
11.07900 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
2.528000 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
2.562000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
13.94000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.117000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
7.693000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
3.537000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
13.50600 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.014000 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
3.047000 1.000000
contraction shell=S num_primitives=1 num_coefficients=1
16.12100 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
3.659000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
8.927000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
4.181000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
15.86000 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
3.572000 1.000000
