atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.00575 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0210 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0420 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0777 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1250 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.1750 1.0000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.00910 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.00458 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.01440 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0286 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.0694 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.1430 1.0000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.0145 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0091 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0247 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0487 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1180 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.2390 1.0000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.0186 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0115 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0329 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0579 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1420 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.2950 1.0000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.0224 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0111 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0444 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0796 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1790 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.3720 1.0000
