atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.00589 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0225 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0494 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0858 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1250 1.0000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.0133 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0423 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0915 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1670 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1820 1.0000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.00985 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.00496 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0149 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0313 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.0885 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.1770 1.0000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.0152 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0097 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0257 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0544 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.1500 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.2730 1.0000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.0192 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0128 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0342 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0748 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.2020 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.3510 1.0000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.0235 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0155 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0483 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.0935 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.2250 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.4520 1.0000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.0280 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0192 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0639 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1370 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.2910 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.5870 1.0000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.0319 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.0223 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.0773 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.1710 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.3480 1.0000
contraction shell=H num_primitives=1 num_coefficients=1
0.7020 1.0000
