atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.00621 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0246 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0545 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.0928 1.000000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.0127 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0472 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.101 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.178 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.0100 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.00546 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0150 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.0411 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.111 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.0155 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0103 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0257 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.0721 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.178 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.0192 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0136 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0368 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.0876 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.219 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.0234 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0163 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0534 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.122 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.276 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.0280 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0199 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0731 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.184 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.359 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.0337 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0251 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0998 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.311 1.000000
contraction shell=G num_primitives=1 num_coefficients=1
0.502 1.000000
