atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.00621 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0268 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0577 1.000000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.0126 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0524 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1070 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.00986 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.00571 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0183 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.0542 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.0151 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0105 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0314 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.0944 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.0186 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0140 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0486 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.1210 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.0228 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0167 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0710 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.1750 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.0276 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0203 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0997 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.2730 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.0339 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0255 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1360 1.000000
contraction shell=F num_primitives=1 num_coefficients=1
0.4620 1.000000
