atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.00725 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02730 1.000000
atom=He
contraction shell=S num_primitives=1 num_coefficients=1
0.0177 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0480 1.000000
atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.00924 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.00593 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.02380 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.0138 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0108 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0415 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.0167 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0144 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0647 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.0206 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0171 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.0930 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.0250 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0208 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1310 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.0311 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.0262 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.1810 1.000000
