atom=H
contraction shell=P num_primitives=1 num_coefficients=1
1.000000 1.000000
atom=He
contraction shell=P num_primitives=1 num_coefficients=1
1.000000 1.000000
atom=Li
contraction shell=D num_primitives=1 num_coefficients=1
0.200000 1.000000
atom=Be
contraction shell=D num_primitives=1 num_coefficients=1
0.400000 1.000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
0.700000 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
0.750000 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
0.800000 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
0.850000 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
0.900000 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
0.950000 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.325000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.550000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
0.600000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
0.700000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
0.750000 1.000000
