atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.048273 1.000000
atom=Li
contraction shell=S num_primitives=1 num_coefficients=1
0.010700 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.007800 1.000000
atom=Be
contraction shell=P num_primitives=1 num_coefficients=1
0.017342 1.000000
atom=B
contraction shell=P num_primitives=1 num_coefficients=1
0.019 1.000000
atom=C
contraction shell=P num_primitives=1 num_coefficients=1
0.034 1.000000
atom=N
contraction shell=P num_primitives=1 num_coefficients=1
0.048 1.000000
atom=O
contraction shell=P num_primitives=1 num_coefficients=1
0.059 1.000000
atom=F
contraction shell=P num_primitives=1 num_coefficients=1
0.074 1.000000
atom=Ne
contraction shell=P num_primitives=1 num_coefficients=1
0.089 1.000000
