atom=H
contraction shell=P num_primitives=1 num_coefficients=1
1.000000 1.000000
atom=He
contraction shell=P num_primitives=1 num_coefficients=1
1.000000 1.000000
atom=Be
contraction shell=D num_primitives=1 num_coefficients=1
0.320000 1.000000
atom=B
contraction shell=D num_primitives=1 num_coefficients=1
0.500000 1.000000
atom=C
contraction shell=D num_primitives=1 num_coefficients=1
0.720000 1.000000
atom=N
contraction shell=D num_primitives=1 num_coefficients=1
0.980000 1.000000
atom=O
contraction shell=D num_primitives=1 num_coefficients=1
1.280000 1.000000
atom=F
contraction shell=D num_primitives=1 num_coefficients=1
1.620000 1.000000
atom=Ne
contraction shell=D num_primitives=1 num_coefficients=1
2.000000 1.000000
atom=Na
contraction shell=D num_primitives=1 num_coefficients=1
0.157000 1.000000
atom=Mg
contraction shell=D num_primitives=1 num_coefficients=1
0.234000 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.311000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.388000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
0.465000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
0.542000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
0.619000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
0.696000 1.000000
