atom=K
contraction shell=D num_primitives=1 num_coefficients=1
0.100000 1.000000
atom=Ca
contraction shell=D num_primitives=1 num_coefficients=1
0.100000 1.000000
atom=Ga
contraction shell=D num_primitives=1 num_coefficients=1
0.207000 1.000000
atom=Ge
contraction shell=D num_primitives=1 num_coefficients=1
0.246000 1.000000
atom=As
contraction shell=D num_primitives=1 num_coefficients=1
0.293000 1.000000
atom=Se
contraction shell=D num_primitives=1 num_coefficients=1
0.338000 1.000000
atom=Br
contraction shell=D num_primitives=1 num_coefficients=1
0.389000 1.000000
atom=Kr
contraction shell=D num_primitives=1 num_coefficients=1
0.443000 1.000000
atom=Rb
contraction shell=D num_primitives=1 num_coefficients=1
0.110000 1.000000
atom=Sr
contraction shell=D num_primitives=1 num_coefficients=1
0.110000 1.000000
atom=In
contraction shell=D num_primitives=1 num_coefficients=1
0.160000 1.000000
atom=Sn
contraction shell=D num_primitives=1 num_coefficients=1
0.183000 1.000000
atom=Sb
contraction shell=D num_primitives=1 num_coefficients=1
0.211000 1.000000
atom=Te
contraction shell=D num_primitives=1 num_coefficients=1
0.237000 1.000000
atom=I
contraction shell=D num_primitives=1 num_coefficients=1
0.266000 1.000000
atom=Xe
contraction shell=D num_primitives=1 num_coefficients=1
0.297000 1.000000
atom=Tl
contraction shell=D num_primitives=1 num_coefficients=1
0.146000 1.000000
atom=Pb
contraction shell=D num_primitives=1 num_coefficients=1
0.164000 1.000000
atom=Bi
contraction shell=D num_primitives=1 num_coefficients=1
0.185000 1.000000
atom=Po
contraction shell=D num_primitives=1 num_coefficients=1
0.204000 1.000000
atom=At
contraction shell=D num_primitives=1 num_coefficients=1
0.225000 1.000000
atom=Rn
contraction shell=D num_primitives=1 num_coefficients=1
0.247000 1.000000
