atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.0498 1.0
contraction shell=P num_primitives=1 num_coefficients=1
0.3560 1.0
atom=C
contraction shell=P num_primitives=1 num_coefficients=1
0.0311 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.5870 1.0
atom=N
contraction shell=P num_primitives=1 num_coefficients=1
0.0533 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.7360 1.0
atom=O
contraction shell=P num_primitives=1 num_coefficients=1
0.0673 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.9610 1.0
atom=F
contraction shell=P num_primitives=1 num_coefficients=1
0.0737 1.0
contraction shell=D num_primitives=1 num_coefficients=1
1.5770 1.0
atom=Si
contraction shell=P num_primitives=1 num_coefficients=1
0.0237 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.2960 1.0
atom=P
contraction shell=P num_primitives=1 num_coefficients=1
0.0298 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.3640 1.0
atom=S
contraction shell=P num_primitives=1 num_coefficients=1
0.0347 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.4960 1.0
atom=Cl
contraction shell=P num_primitives=1 num_coefficients=1
0.0467 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.6480 1.0
atom=Ge
contraction shell=P num_primitives=1 num_coefficients=1
0.0209 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.2460 1.0
atom=As
contraction shell=P num_primitives=1 num_coefficients=1
0.0263 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.2860 1.0
atom=Se
contraction shell=P num_primitives=1 num_coefficients=1
0.0328 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.3630 1.0
atom=Br
contraction shell=P num_primitives=1 num_coefficients=1
0.0376 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.4340 1.0
atom=Sn
contraction shell=P num_primitives=1 num_coefficients=1
0.0174 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.1860 1.0
atom=Sb
contraction shell=P num_primitives=1 num_coefficients=1
0.0220 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.2070 1.0
atom=Te
contraction shell=P num_primitives=1 num_coefficients=1
0.0274 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.2500 1.0
atom=I
contraction shell=P num_primitives=1 num_coefficients=1
0.0308 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.2940 1.0
atom=Pb
contraction shell=P num_primitives=1 num_coefficients=1
0.0168 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.1790 1.0
atom=Bi
contraction shell=P num_primitives=1 num_coefficients=1
0.0204 1.0
contraction shell=D num_primitives=1 num_coefficients=1
0.1920 1.0
