atom=H
contraction shell=S num_primitives=1 num_coefficients=1
0.036000 1.000000
atom=Li
contraction shell=SP num_primitives=1 num_coefficients=2
0.007400 1.000000 1.000000
atom=Be
contraction shell=SP num_primitives=1 num_coefficients=2
0.020700 1.000000 1.000000
atom=B
contraction shell=SP num_primitives=1 num_coefficients=2
0.031500 1.000000 1.000000
atom=C
contraction shell=SP num_primitives=1 num_coefficients=2
0.043800 1.000000 1.000000
atom=N
contraction shell=SP num_primitives=1 num_coefficients=2
0.063900 1.000000 1.000000
atom=O
contraction shell=SP num_primitives=1 num_coefficients=2
0.084500 1.000000 1.000000
atom=F
contraction shell=SP num_primitives=1 num_coefficients=2
0.107600 1.000000 1.000000
atom=Ne
contraction shell=SP num_primitives=1 num_coefficients=2
0.130000 1.000000 1.000000
atom=Na
contraction shell=SP num_primitives=1 num_coefficients=2
0.007600 1.000000 1.000000
atom=Mg
contraction shell=SP num_primitives=1 num_coefficients=2
0.014600 1.000000 1.000000
atom=Al
contraction shell=SP num_primitives=1 num_coefficients=2
0.031800 1.000000 1.000000
atom=Si
contraction shell=SP num_primitives=1 num_coefficients=2
0.033100 1.000000 1.000000
atom=P
contraction shell=SP num_primitives=1 num_coefficients=2
0.034800 1.000000 1.000000
atom=S
contraction shell=SP num_primitives=1 num_coefficients=2
0.040500 1.000000 1.000000
atom=Cl
contraction shell=SP num_primitives=1 num_coefficients=2
0.048300 1.000000 1.000000
atom=Ar
contraction shell=SP num_primitives=1 num_coefficients=2
0.060000 1.000000 1.000000
atom=K
contraction shell=SP num_primitives=1 num_coefficients=2
0.004700 1.000000 1.000000
atom=Ca
contraction shell=SP num_primitives=1 num_coefficients=2
0.007100 1.000000 1.000000
