atom=B
contraction shell=S num_primitives=1 num_coefficients=1
0.019000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.015000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.015000 1.000000
atom=C
contraction shell=S num_primitives=1 num_coefficients=1
0.023000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.021000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.015000 1.000000
atom=N
contraction shell=S num_primitives=1 num_coefficients=1
0.028000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.025000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.015000 1.000000
atom=O
contraction shell=S num_primitives=1 num_coefficients=1
0.032000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.028000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.015000 1.000000
atom=F
contraction shell=S num_primitives=1 num_coefficients=1
0.036000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.029000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.015000 1.000000
atom=Ne
contraction shell=S num_primitives=1 num_coefficients=1
0.040000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.030000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.015000 1.000000
atom=Al
contraction shell=S num_primitives=1 num_coefficients=1
0.01400 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01100 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.01500 1.000000
atom=Si
contraction shell=S num_primitives=1 num_coefficients=1
0.01700 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01400 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.01500 1.000000
atom=P
contraction shell=S num_primitives=1 num_coefficients=1
0.02000 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.01700 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.01500 1.000000
atom=S
contraction shell=S num_primitives=1 num_coefficients=1
0.02300 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.01500 1.000000
atom=Cl
contraction shell=S num_primitives=1 num_coefficients=1
0.02500 1.000000
contraction shell=P num_primitives=1 num_coefficients=1
0.02000 1.000000
contraction shell=D num_primitives=1 num_coefficients=1
0.01500 1.000000
atom=Ar
contraction shell=S num_primitives=1 num_coefficients=1
0.02700 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.02000 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.01500 1.0000
