atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.014288 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.008637 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.029017 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.063337 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.168998 1.0000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.022026 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.014297 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.043539 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.087823 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.218100 1.0000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.030490 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.018393 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.065823 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.109144 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.234084 1.0000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.057032 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.038063 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.079244 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.127709 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.269491 1.0000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.070898 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.046986 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.123007 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.182161 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.319618 1.0000
atom=In
contraction shell=S num_primitives=1 num_coefficients=1
0.014360 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.009189 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.029698 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.055291 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.144360 1.0000
atom=Sn
contraction shell=S num_primitives=1 num_coefficients=1
0.012437 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.014698 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.044488 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.073838 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.175101 1.0000
atom=Sb
contraction shell=S num_primitives=1 num_coefficients=1
0.024439 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.018236 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.051236 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.089046 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.185414 1.0000
atom=Te
contraction shell=S num_primitives=1 num_coefficients=1
0.049732 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.032036 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.062829 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.104284 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.210263 1.0000
atom=I
contraction shell=S num_primitives=1 num_coefficients=1
0.058108 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.037653 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.074797 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.150736 1.0000
contraction shell=G num_primitives=1 num_coefficients=1
0.244249 1.0000
