atom=Ga
contraction shell=S num_primitives=1 num_coefficients=1
0.028748 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.014610 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.034927 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.096955 1.0000
atom=Ge
contraction shell=S num_primitives=1 num_coefficients=1
0.042772 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.025839 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.050929 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.133053 1.0000
atom=As
contraction shell=S num_primitives=1 num_coefficients=1
0.053831 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.037098 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.062640 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.158238 1.0000
atom=Se
contraction shell=S num_primitives=1 num_coefficients=1
0.066492 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.041583 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.077648 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.191546 1.0000
atom=Br
contraction shell=S num_primitives=1 num_coefficients=1
0.080821 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.051052 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.096735 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.259289 1.0000
atom=In
contraction shell=S num_primitives=1 num_coefficients=1
0.025995 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.014983 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.029536 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.082676 1.0000
atom=Sn
contraction shell=S num_primitives=1 num_coefficients=1
0.034771 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.025221 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.041850 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.107480 1.0000
atom=Sb
contraction shell=S num_primitives=1 num_coefficients=1
0.042838 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.032294 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.053005 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.126031 1.0000
atom=Te
contraction shell=S num_primitives=1 num_coefficients=1
0.054564 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.036271 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.066256 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.148157 1.0000
atom=I
contraction shell=S num_primitives=1 num_coefficients=1
0.065739 1.0000
contraction shell=P num_primitives=1 num_coefficients=1
0.041835 1.0000
contraction shell=D num_primitives=1 num_coefficients=1
0.073831 1.0000
contraction shell=F num_primitives=1 num_coefficients=1
0.193973 1.0000
