atom=Na
contraction shell=D num_primitives=1 num_coefficients=1
0.090000 1.000000
atom=Mg
contraction shell=D num_primitives=1 num_coefficients=1
0.090000 1.000000
atom=Al
contraction shell=D num_primitives=1 num_coefficients=1
0.390000 1.000000
atom=Si
contraction shell=D num_primitives=1 num_coefficients=1
0.390000 1.000000
atom=P
contraction shell=D num_primitives=1 num_coefficients=1
0.390000 1.000000
atom=S
contraction shell=D num_primitives=1 num_coefficients=1
0.390000 1.000000
atom=Cl
contraction shell=D num_primitives=1 num_coefficients=1
0.390000 1.000000
atom=Ar
contraction shell=D num_primitives=1 num_coefficients=1
0.390000 1.000000
