#!/bin/csh -f

if (! $?ECCE_HOME) then
  echo "ERROR: ECCE_HOME must be set prior to running Viewer."
  echo "       Check your ~/.cshrc or ~/.mycshrc file for the correct path"
  echo "       to runtime_setup, or contact your site ECCE administrator"
  echo ""
  exit
endif

# this sets ECCE_SYSDIR
source $ECCE_HOME/scripts/ecce_env

if ( $ECCE_SYSDIR == "unsupported" ) then
  echo "ERROR: Host is not supported by this ECCE installation."
  echo -n "       Host platform: "
  $ECCE_HOME/scripts/sysdir
  echo ""
  exit
endif

cd $ECCE_HOME/${ECCE_SYSDIR}bin
setenv ECCE_INVOKE_VIEWER
setenv ECCE_INVOKE_FROMECCE
./builder $*
