#!/usr/bin/env python3
"""MINFF topology builder tests (issue #241).

For each system the types and charges that scripts/minff_topology.py writes
into min.itp are compared with atomipy's own pipeline run directly
(oracle.py), then the result goes through `gmx grompp` and a 200-step
steepest-descent minimisation, whose potential energy must be finite and
decrease.  Montmorillonite is also compared with the itp the MINFF authors
ship for the same structure (generated by their MATLAB library).

Needs a python with atomipy (ECCE_ATOMIPY_PYTHON, else python3), gmx, and
min.ff (fetched to ~/.cache/ecce/minff, or ECCE_MINFF_DIR).
Exit status 77 (CTest SKIP) if one of them is missing.
"""
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SCRIPT = os.path.join(ROOT, "scripts", "minff_topology.py")
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import minff_topology as mt  # noqa: E402

EM_MDP = """integrator = steep
nsteps = 200
emtol = 10
emstep = 0.001
cutoff-scheme = verlet
coulombtype = PME
rcoulomb = 0.9
rvdw = 0.9
vdwtype = cut-off
DispCorr = EnerPres
pbc = xyz
periodic-molecules = yes
nstenergy = 10
nstlog = 10
"""
failures = []


def check(cond, msg):
    print(("ok   " if cond else "FAIL ") + msg)
    if not cond:
        failures.append(msg)


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def build(cell, out, *args):
    r = run([PY, SCRIPT, "build", cell, "-o", out, *args])
    if r.returncode:
        print(r.stderr[-2000:])
    check(r.returncode == 0, "build " + os.path.basename(cell) + " " + " ".join(args))
    return json.loads(r.stdout) if r.returncode == 0 else None


def oracle(cell, *args):
    r = run([PY, os.path.join(HERE, "oracle.py"), cell, *map(str, args)])
    if r.returncode:
        print(r.stderr[-2000:])
        raise SystemExit("oracle failed")
    return json.loads(r.stdout)


def compare(out, ref, label):
    got = mt.read_itp_atoms(os.path.join(out, "min.itp"))
    check(len(got) == len(ref["types"]), "%s: %d atoms" % (label, len(got)))
    bad = [i for i, (t, q) in enumerate(got)
           if t != ref["types"][i] or abs(q - ref["charges"][i]) > 2e-6]
    check(not bad, "%s: types and charges equal atomipy's (%d differ)" % (label, len(bad)))
    tot = sum(q for _, q in got)
    check(abs(tot - sum(ref["charges"])) < 1e-4,
          "%s: total charge %.4f vs atomipy %.4f" % (label, tot, sum(ref["charges"])))
    return tot


def minimise(out, label, charged=False):
    with open(os.path.join(out, "em.mdp"), "w") as f:
        f.write(EM_MDP)
    r = run(["gmx", "grompp", "-f", "em.mdp", "-c", "conf.gro", "-p", "topol.top",
             "-o", "em.tpr", "-maxwarn", "1" if charged else "0"], cwd=out)
    check(r.returncode == 0, label + ": grompp" + (" (only the net-charge warning)" if charged else ", no warnings"))
    if r.returncode:
        print(r.stderr[-1500:])
        return
    r = run(["gmx", "mdrun", "-deffnm", "em", "-nt", "1"], cwd=out)
    check(r.returncode == 0, label + ": mdrun")
    r = run(["gmx", "energy", "-f", "em.edr", "-o", "pe.xvg"], cwd=out, input="Potential\n0\n")
    pe = [float(l.split()[1]) for l in open(os.path.join(out, "pe.xvg"))
          if l.strip() and l[0] not in "#@"]
    check(len(pe) > 2 and all(map(math.isfinite, pe)), label + ": energies finite")
    check(pe[-1] < pe[0], label + ": energy decreases %.4g -> %.4g kJ/mol" % (pe[0], pe[-1]))


def mineral_only(src, dst):
    """The MIN residues of a hydrated .gro (water and ions dropped)."""
    L = open(src).read().splitlines()
    keep = [l for l in L[2:-1] if l[5:10].strip() == "MIN"]
    open(dst, "w").write("\n".join([L[0], str(len(keep))] + keep + [L[-1]]) + "\n")


def main():
    global PY
    PY = mt.find_atomipy_python()
    if not PY:
        print("SKIP: atomipy is not installed (pip install atomipy)")
        return 77
    if not shutil.which("gmx"):
        print("SKIP: gmx is not installed")
        return 77
    try:
        ffdir = mt.minff_dir()
    except mt.MinffError as e:
        print("SKIP: %s" % e)
        return 77
    uc = os.path.join(ffdir, "Systems", "UC_conf")
    work = tempfile.mkdtemp(prefix="minfftest-")
    os.environ["ECCE_MINFF_REEXEC"] = "1"      # PY already has atomipy

    # 1. kaolinite, general MINFF k=500
    cell = os.path.join(uc, "Kaolinite_GII_0.0487.pdb")
    out = os.path.join(work, "kaol")
    s = build(cell, out, "--replicate", "4", "3", "3")
    if s:
        compare(out, oracle(cell, 4, 3, 3), "kaolinite")
        check(abs(s["total_charge"]) < 1e-4 and not s["untyped_atoms"],
              "kaolinite: neutral, no untyped atoms")
        minimise(out, "kaolinite")

    # 2. montmorillonite, tailored MINFF; the mineral layer of the authors'
    #    hydrated example (UC_conf has no montmorillonite)
    cell = os.path.join(work, "montmorillonite.gro")
    mineral_only(os.path.join(ffdir, "Systems", "conf", "preem27.gro"), cell)
    out = os.path.join(work, "mont")
    s = build(cell, out, "--variant", "tminff", "--mineral", "Montmorillonite")
    if s:
        compare(out, oracle(cell, 1, 1, 1), "montmorillonite")
        ref = mt.read_itp_atoms(os.path.join(ffdir, "Systems", "itp", "min27.itp"))
        got = mt.read_itp_atoms(os.path.join(out, "min.itp"))
        check(len(ref) == len(got) and all(
            a[0] == b[0] and abs(a[1] - b[1]) < 1e-4 for a, b in zip(got, ref)),
            "montmorillonite: types and charges equal the MATLAB min27.itp")
        check(s["total_charge"] == -48.0 and not s["untyped_atoms"],
              "montmorillonite: charge -48 (48 Mg), no untyped atoms")
        check("Montmorillonite_k500" in open(os.path.join(out, "topol.top")).read(),
              "montmorillonite: topol.top selects Montmorillonite_k500")
        minimise(out, "montmorillonite", charged=True)

    # 3. Al -> Mg substitution in pyrophyllite
    cell = os.path.join(uc, "Pyrophyllite_Lee_Guggenheim_1981_GII_0.071.pdb")
    out = os.path.join(work, "pyro")
    s = build(cell, out, "--replicate", "4", "3", "3", "--substitute", "Al", "Mgo", "4",
              "--seed", "1")
    if s:
        compare(out, oracle(cell, 4, 3, 3, "Al", "Mgo", 4, 1, 5.5), "substitution")
        check(s["type_counts"].get("Mgo") == 4 and abs(s["total_charge"] + 4) < 1e-4,
              "substitution: 4 Mgo, total charge -4")
        minimise(out, "substitution", charged=True)

    # 4. the other angle constants and the mineral list are selectable
    out = os.path.join(work, "k1500")
    s = build(os.path.join(uc, "Kaolinite_GII_0.0487.pdb"), out, "--replicate", "4", "3", "3",
              "--angle-k", "1500")
    if s:
        itp = open(os.path.join(out, "min.itp")).read()
        check("1500.00" in itp and "GMINFF_k1500" in open(os.path.join(out, "topol.top")).read(),
              "k=1500 reaches the angles and topol.top")
    check("Kaolinite" in mt.list_minerals(500, ffdir), "mineral list has Kaolinite")

    if not failures:
        shutil.rmtree(work, ignore_errors=True)
    else:
        print("work directory kept: " + work)
    print("%d failure(s)" % len(failures))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
