name: wixhelp
on: workflow_dispatch
jobs:
  h:
    runs-on: windows-latest
    steps:
      - shell: pwsh
        run: |
          dotnet tool install --global wix --version 5.0.2
          wix build -? | Select-String -Pattern 'sval|sice|ice|suppress|-ext|-arch|-o' 
